<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fix="http://www.cboe.com/fix/xslt"
                >

<!-- @author Dmitry Volpyansky

     must be built with JDK 1.4.1 and Saxon XSLT version 7.4 from http://saxon.sourceforge.net/

     classpath needs to include /client/cfix/generator/saxon7.jar and /client/cfix/generator/saxon7_jdom.jar

     command line example: java net.sf.saxon.Transform CboeFIX42.xml Fix_Class_FixHelper_Main.xsl IMPLS_DIRECTORY="/client/cfix/impls"

     the IMPLS_DIRECTORY parameter specifies the output directory
-->

<xsl:param name="IMPLS_DIRECTORY">/tmp</xsl:param>

<xsl:output method="text" encoding="UTF-8" indent="no" name="text"/>

<xsl:strip-space elements="*"/>

<xsl:template match="text()"/>

<xsl:include href="Fix_Helper.xsl"/>

<xsl:template match="fix/fields">
<xsl:result-document href="file://{$IMPLS_DIRECTORY}/com/cboe/cfix/fix/fix{/fix/@versiontag}/generated/helpers/FixFieldHelper.java" format="text">
<xsl:variable name="longestName">
  <xsl:call-template name="fix:longestLengthString">
    <xsl:with-param name="nodeset" select="field/@name"/>
  </xsl:call-template>
</xsl:variable>
package com.cboe.cfix.fix.fix<xsl:value-of select="/fix/@versiontag"/>.generated.helpers;

/**
 * FixFieldHelper.java
 *
 * @author Dmitry Volpyansky
 *
 *
 */

/**
 * This GENERATED file implements FIX Protocol's Field Tag lookups and other helper functions.
 *
 * WARNING: This entire file is completely generated by XSLT stylesheets from CboeFIX<xsl:value-of select="/fix/@versiontag"/>.xml file.
 *
 */

import com.cboe.cfix.fix.fix<xsl:value-of select="/fix/@versiontag"/>.generated.fields.*;

public final class FixFieldHelper
{   <xsl:text/>
    public static final String TO_STRING_NO_MATCH     = "NO MATCH";
    public static final String TO_STRING_UNKNOWN_TAG  = "UNKNOWN TAG";

    public static String getTagName(int tag)<xsl:text/>
    {   <xsl:text/>
        switch (tag)
        {   <xsl:text/>
            <xsl:for-each select="field">
            case <xsl:value-of select="fix:rightPad(concat(fix:buildFixFieldName(@name),'.TagID'), $longestName+6+3+5)"/>: return <xsl:value-of select="fix:buildFixFieldName(@name)"/>.TagName; <xsl:text/>
            </xsl:for-each>
        }

        return "UNKNOWN TAG(" + tag + ")";
    }
}
</xsl:result-document>
</xsl:template>

</xsl:stylesheet>
