#!/bin/ksh

# -------------------- Constants --------------------

USER_ID=HD1:HD1
PROG=`basename $0`
PROG=${PROG%Worker}

# Error codes from /usr/include/errno.h
EINVAL=22

# -------------------- Main Program --------------------

if [ -z "$1" ] || [ "$1" = "-h" ] ; then
    print -u2 "Usage: $PROG [ -s id:password ] command [args...]"
    print -u2 "Example:"
    print -u2 "       $PROG help"
    exit $EINVAL
fi

if [ "$1" = "-s" ] ; then
    shift
    if ! [[ $1 = *:* ]] ; then
        print -u2 "$PROG: Switch -s requires userId:password argument"
        exit $EINVAL
    fi
    USER_ID=$1
    shift
fi

ORBNAME=${SBT_PREFIX}sacas01v2${HOSTNAME}

ar -s $USER_ID ${ORBNAME} $*
