#!/bin/ksh
# v2quickstartcfix - script to quickstart cfix${1}
# usage: v2quickstartcfix 01

if [[ "$1" != [0-9][0-9] ]] ; then
    print -u2 "Usage: $( basename $0 ) <engineNumber>"
    exit 1
fi

ENGINE=cfix${1}
THIS_CLIENT=cfix

. ClientFunctions
setQuickstart
startClient
