#!/bin/ksh
# v2stopcfix - script to stop cfix${1}
# usage: v2stopcfix 01

if [[ "$1" != [0-9][0-9] ]] ; then
    print -u2 "Usage: $( basename $0 ) <engineNumber>"
    exit 1
fi

ENGINE=cfix${1}
THIS_CLIENT=cfix

# Remove status file from Patrol directory
ENGINE_LIST_DIR=$INFRA_HOME/v2run_dir/log/engineList
\rm -f $ENGINE_LIST_DIR/$ENGINE

. $( dirname $0 )/ClientFunctions
stopClient
