#!/bin/ksh
# v2startcfix - script to start cfix${1}
# usage: v2startcfix 01

if [[ "$1" != [0-9][0-9] ]] ; then
    print -u2 "Usage: $( basename $0 ) <engineNumber>"
    exit 1
fi

ENGINE=cfix${1}
THIS_CLIENT=cfix

# Make status file for Patrol to see
ENGINE_LIST_DIR=$INFRA_HOME/v2run_dir/log/engineList
if [ ! -e $ENGINE_LIST_DIR ] ; then
    mkdir -m775 $ENGINE_LIST_DIR
fi
touch $ENGINE_LIST_DIR/$ENGINE

# Start the client
. $( dirname $0 )/ClientFunctions
clearQuickstart
startClient
