#!/bin/ksh
# v2startmdcas - script to start mdcas${1}
# usage : v2startmdcas 01


if [[ "$1" != [0-9][0-9] ]] ; then
    print -u2 "Usage: $( basename $0 ) <engineNumber>"
    exit 1
fi

ENGINE=mdcas${1}
THIS_CLIENT=mdcas

. $( dirname $0 )/ClientFunctions
clearQuickstart
startClient
