/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cboe_util_UniqueNumberGenerator */

#ifndef _Included_com_cboe_util_UniqueNumberGenerator
#define _Included_com_cboe_util_UniqueNumberGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cboe_util_UniqueNumberGenerator
 * Method:    getProcessID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cboe_util_UniqueNumberGenerator_getProcessID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
