// -----------------------------------------------------------------------------------
// Source file: BusinessModelCollectionEvent.java
//
// PACKAGE: com.cboe.interfaces.presentation.common.businessModels;
//
// -----------------------------------------------------------------------------------
// Copyright (c) 2001 The Chicago Board Options Exchange. All Rights Reserved.
// -----------------------------------------------------------------------------------
package com.cboe.interfaces.presentation.common.businessModels;

import com.cboe.interfaces.presentation.common.businessModels.BusinessModel;

/**
 * Interface for an event that can be generated by the BusinessModelCollection object
 */
public interface BusinessModelCollectionEvent 
{
    /**
     * Gets the model for the event
     * @return BusinessModel event occurred for.
     */
    public BusinessModel getElement();
    /**
     * Returns the BusinessModelCollection on which event occurred.
     * @return Object event occured on.
     */
    public Object getSource();
    /**
     * Returns a String representation of this BusinessModelCollectionEvent.
     * @return String representation of this BusinessModelCollectionEvent.
     */
    public String toString();
}