package com.cboe.domain.messaging;

/**
 * 
 * @author morrow
 * 
 */
public enum Topic implements MessageTopic
{

	// *************** ICS TOPICS ***************//
	CENTRAL_LOGGING_MESSAGE,
	PROCESS_WATCHER,
	QUEUE_INSTRUMENTOR_BLOCK,
	EVENT_CHANNEL_INSTRUMENTOR_BLOCK,
	THREAD_INSTRUMENTOR_BLOCK,
	NETWORK_CONNECTION_INSTRUMENTOR_BLOCK,
	HEAP_INSTRUMENTOR_BLOCK,
	METHOD_INSTRUMENTOR_BLOCK,
	COUNT_INSTRUMENTOR_BLOCK,
	JMX_INSTRUMENTOR_BLOCK,
	JSTAT_INSTRUMENTOR_BLOCK,
	RATE_INSTRUMENTOR_BLOCK,

	ACCEPT_ORB_NAME_ALIASES,
	ACCEPT_NEW_ORB_NAME_ALIAS,
	ACCEPT_DELETE_ORB_NAME_ALIAS,
	ACCEPT_CHANGED_ORB_NAME_ALIAS,

	ORB_NAME_ALIASES,
	NEW_ORB_NAME_ALIAS,
	DELETE_ORB_NAME_ALIAS,
	CHANGED_ORB_NAME_ALIAS,
	PUBLISH_ORB_NAME_ALIAS,

	ACCEPT_LOGICAL_ORB_NAMES,
	ACCEPT_NEW_LOGICAL_ORB_NAME,
	ACCEPT_DELETE_LOGICAL_ORB_NAME,
	ACCEPT_CHANGED_LOGICAL_ORB_NAME,

	NEW_LOGICAL_ORB_NAME,
	DELETE_LOGICAL_ORB_NAME,
	CHANGED_LOGICAL_ORB_NAME,
	PUBLISH_LOGICAL_ORB_NAME,

	ALARM_NOTIFICATION,
	ALARM_NOTIFICATION_ONE,

	ACCEPT_WATCHDOGS,
	ACCEPT_NEW_WATCHDOG,
	ACCEPT_DELETE_WATCHDOG,
	ACCEPT_CHANGED_WATCHDOG,

	WATCHDOGS,
	NEW_WATCHDOG,
	DELETE_WATCHDOG,
	CHANGED_WATCHDOG,
	PUBLISH_WATCHDOG,

	QUEUE_INSTRUMENTOR_SUMMARY,
	EVENT_CHANNEL_INSTRUMENTOR_SUMMARY,
	THREAD_INSTRUMENTOR_SUMMARY,
	NETWORK_CONNECTION_INSTRUMENTOR_SUMMARY,
	HEAP_INSTRUMENTOR_SUMMARY,
	METHOD_INSTRUMENTOR_SUMMARY,
	COUNT_INSTRUMENTOR_SUMMARY,
	JMX_INSTRUMENTOR_SUMMARY,
	JSTAT_INSTRUMENTOR_SUMMARY,

	QUEUE_INSTRUMENTOR_DETAILS,
	EVENT_CHANNEL_INSTRUMENTOR_DETAILS,
	THREAD_INSTRUMENTOR_DETAILS,
	NETWORK_CONNECTION_INSTRUMENTOR_DETAILS,
	HEAP_INSTRUMENTOR_DETAILS,
	METHOD_INSTRUMENTOR_DETAILS,
	COUNT_INSTRUMENTOR_DETAILS,
	JMX_INSTRUMENTOR_DETAILS,
	JSTAT_INSTRUMENTOR_DETAILS,
	RATE_INSTRUMENTOR_DETAILS,

	SUBSCRIBE_ORB,
	UNSUBSCRIBE_ORB,
	SESSION_CLEANUP,
	PUBLISH_SUMMARY,
	PUBLISH_DETAILS,

	ACCEPT_DEFINITIONS,
	ACCEPT_NEW_DEFINITION,
	ACCEPT_CHANGED_DEFINITION,
	ACCEPT_DELETE_DEFINITION,

	ACCEPT_CONDITIONS,
	ACCEPT_NEW_CONDITION,
	ACCEPT_CHANGED_CONDITION,
	ACCEPT_DELETED_CONDITION,

	ACCEPT_CALCULATION,
	ACCEPT_NEW_CALCULATION,
	ACCEPT_CHANGED_CALCULATION,
	ACCEPT_DELETED_CALCULATION,

	ACCEPT_ALARM_ACTIVATION,
	ACCEPT_NEW_ACTIVATION,
	ACCEPT_CHANGED_ACTIVATION,
	ACCEPT_DELETE_ACTIVATION,

	ACCEPT_ALARM_ACTIVATION_ASSIGNMENT,
	ACCEPT_NEW_ACTIVATION_ASSIGNMENT,
	ACCEPT_CHANGED_ACTIVATION_ASSIGNMENT,
	ACCEPT_DELETE_ACTIVATION_ASSIGNMENT,

	CREATE_DEFINITION,
	PUBLISH_DEFINITION,
	UPDATE_DEFINITION,
	DELETE_DEFINITION,

	CREATE_CONDITION,
	PUBLISH_CONDITION,
	UPDATE_CONDITION,
	DELETE_CONDITION,

	CREATE_CALCULATION,
	UPDATE_CALCULATION,
	DELETE_CALCULATION,
	PUBLISH_CALCULATION,

	CREATE_ACTIVATION,
	PUBLISH_ACTIVATION,
	UPDATE_ACTIVATION,
	DELETE_ACTIVATION,
	ALARM_ACTIVATE,
	ALARM_DEACTIVATE,
	ALARM_ACTIVATION_STATUS,

	CREATE_ACTIVATION_ASSIGNMENT,
	PUBLISH_ACTIVATION_ASSIGNMENT,
	UPDATE_ACTIVATION_ASSIGNMENT,
	DELETE_ACTIVATION_ASSIGNMENT,

	ACCEPT_GROUP_ELEMENTS,
	ACCEPT_GROUP_ADD_ELEMENT,
	ACCEPT_GROUP_UPDATE_ELEMENT,
	ACCEPT_GROUP_REMOVE_ELEMENT,
	ACCEPT_GROUP_ELEMENT_RESULTS,

	CREATE_ELEMENTS_FOR_GROUP,
	ADD_ELEMENTS_TO_GROUP,
	UPDATE_ELEMENT,
	REMOVE_ELEMENTS_FROM_GROUP,
	PUBLISH_ROOT_ELEMENT_FOR_GROUP,
	PUBLISH_ELEMENTS_FOR_GROUP,
	MOVE_ELEMENTS_TO_GROUP,
	COPY_ELEMENTS_TO_GROUP,

	/* Container Topics */
	ALARM_ACTIVATION,
	ALARM_DEFINITION,
	ALARM_CONDITION,
	ALARM_CALCULATION,
	ALARM_CONDITION_COMBINATION

}
