package com.cboe.interfaces.presentation.preferences;

import static com.cboe.interfaces.presentation.preferences.PreferenceConstants.DEFAULT_PATH_SEPARATOR;

/**
 * 
 * @author morrow
 *
 */
public interface BusinessPreferenceConstants
{
	String MRU_SECTION = "MRU";
	String APP_PROPERTIES_SECTION_NAME = "Defaults";
	String APP_PROPERTIES_SESSION_SECTION_NAME = "Session";
	String TIMERS_SECTION_NAME = "Timers";
	String MISC_SECTION = "MiscPref";
	String ORDERS_SECTION = "OrdPref";
	String QUOTES_SECTION = "QtePref";
	String GLOBAL_ORDER_SECTION = "GlblOrdPref";
	String MARKET_DISPLAY_VIEW_SIDE_BY_SIDE_PREF_NAME = "MDViewSideBySide";
	String MULTI_CLASS_TABS_PREF_NAME = "MultiClassTabs";
	String LOCKED_MULTI_CLASS_TABS_PREF_NAME = "LockedMultiClassTabs";
	String HELD_ORDER_STATUS_UPDATE = "HeldOrderStatus" + DEFAULT_PATH_SEPARATOR + "Update";
	String HOS_CONFIRM_ON_WINDOW_CLOSE_PREF_NAME = "HOSCnfrmWndCls";
	String MISC_CLASS_LIST = MISC_SECTION + DEFAULT_PATH_SEPARATOR + "ClssLst";
	String EXECUTE_QTY_CONFIRM = MISC_SECTION + DEFAULT_PATH_SEPARATOR + "ExecQtyConf";
	String ORDER_FILLS_ALERT = MISC_SECTION + DEFAULT_PATH_SEPARATOR + "OrdFilAlrt";
	String RFQ_ALERT = MISC_SECTION + DEFAULT_PATH_SEPARATOR + "RFQAlrt";
	String ACCOUNT = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "Acct";
	String BRANCH = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "Brnch";
	String CMTA = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "CMTA";
	String CORRESPONDENT_ID = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "CorspdntId";
	String CROSS_ALERT = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "XAlrt";
	String OPTIONAL_DATA = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "OptData";
	String ORDER_QTY_CONFIRM = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "QtyConf";
	String PRINT_FILLS = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "PrntFil";
	String SUB_ACCOUNT = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "SubAcct";
	String ORDER_SIZE = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "OrdSz";
	String CLEARING_FIRM = ORDERS_SECTION + DEFAULT_PATH_SEPARATOR + "ClearingFirm";
	String QUOTE_CLASS_LIST = QUOTES_SECTION + DEFAULT_PATH_SEPARATOR + "ClssLst";
	String QUOTE_QTY_CONFIRM = QUOTES_SECTION + DEFAULT_PATH_SEPARATOR + "QtyConf";
	String QUOTE_SPREAD = QUOTES_SECTION + DEFAULT_PATH_SEPARATOR + "QteSprd";
	String ORDER_SEQUENCE_NUMBER = GLOBAL_ORDER_SECTION + DEFAULT_PATH_SEPARATOR + "SeqNum";
	String KEEP_ORDER_SCREEN_UP = GLOBAL_ORDER_SECTION + DEFAULT_PATH_SEPARATOR + "KeepOrderUp";
	String STRATEGY_HIT_BID_OFFER = GLOBAL_ORDER_SECTION + DEFAULT_PATH_SEPARATOR + "StrategyMktDspHitBidOffer";
	String MARKET_DISPLAY_VIEW_SIDE_BY_SIDE = MISC_SECTION + DEFAULT_PATH_SEPARATOR + MARKET_DISPLAY_VIEW_SIDE_BY_SIDE_PREF_NAME;
	String ALLOW_MULTIPLE_CLASSES_DEFAULT = MISC_SECTION + DEFAULT_PATH_SEPARATOR + MULTI_CLASS_TABS_PREF_NAME;
	String HOS_CONFIRM_ON_WINDOW_CLOSE = MISC_SECTION + DEFAULT_PATH_SEPARATOR + HOS_CONFIRM_ON_WINDOW_CLOSE_PREF_NAME;
	String DEFAULT_PRODUCT_SESSION = APP_PROPERTIES_SECTION_NAME + DEFAULT_PATH_SEPARATOR + "DefPrdSes";
	String DEFAULT_PRODUCT_TYPE = APP_PROPERTIES_SECTION_NAME + DEFAULT_PATH_SEPARATOR + "DefPrdType";

	String TRADING_SESSION_PREF_NAME = "DefaultTradingSession";
	String C2_EXCHANGE_PREF_NAME = "IsC2Exchange";

	// EOP Preferences
	String EOP_TRADING_SESSION_PREF_NAME = "EOPTradingSession";
	String EOP_PRODUCT_TYPE_PREF_NAME = "EOPProductType";
	String EOP_PRODUCT_CLASSKEYS_PREF_NAME = "EOPProductClassKeys";
	String EOP_GROUPS_PREF_NAME = "EOPGroups";

	String AUTO_CANCEL = "AUTO_CANCEL";
	String AUTO_REMOVE_CANCEL_ORDER = "AutoRemoveCancelOrder";

	// Printer Preferences
	String AUTO_PRINT_DROP_COPY = "AutoPrintDropCopy";
	String PRINT_PACKAGE_FILL = "PrintPackageFill";
	String NUM_DROPCOPY_PRINTS = "NumberDropCopyPrints";
    String NUM_DROPCOPY_PRINTS_SECONDARY = "NumberDropCopyPrintsSecondary";
    String SMALL_DROP_COPY = "SmallDropCopy";
	String PRINTER_SMALL = "PrinterSmall";
	String PRINTER_LARGE = "PrinterLarge";
    String PRINTER_LARGE_SECONDARY = "PrinterLargeSecondary";

    // OMT Preferences
	String OMT_SECTION = "OMTPref";
	String OMT_AUTO_CANCEL = OMT_SECTION + DEFAULT_PATH_SEPARATOR + AUTO_CANCEL;
	String OMT_AUTO_PRINT_DCROP_COPY = OMT_SECTION + DEFAULT_PATH_SEPARATOR + AUTO_PRINT_DROP_COPY;
	String OMT_PRINT_PACKAGE_FILL = OMT_SECTION + DEFAULT_PATH_SEPARATOR + PRINT_PACKAGE_FILL;
	String OMT_NUMBER_DROP_COPY_PRINTS = OMT_SECTION + DEFAULT_PATH_SEPARATOR + NUM_DROPCOPY_PRINTS;
    String OMT_NUMBER_DROP_COPY_PRINTS_SECONDARY = OMT_SECTION + DEFAULT_PATH_SEPARATOR + NUM_DROPCOPY_PRINTS_SECONDARY;
    String OMT_SMALL_DCROP_COPY = OMT_SECTION + DEFAULT_PATH_SEPARATOR + SMALL_DROP_COPY;
	String OMT_PRINTER_SMALL = OMT_SECTION + DEFAULT_PATH_SEPARATOR + PRINTER_SMALL;
	String OMT_PRINTER_LARGE = OMT_SECTION + DEFAULT_PATH_SEPARATOR + PRINTER_LARGE;
    String OMT_PRINTER_LARGE_SECONDARY = OMT_SECTION + DEFAULT_PATH_SEPARATOR + PRINTER_LARGE_SECONDARY;
    String OMT_DISPLAY_AUDIT_HISTORY = OMT_SECTION + DEFAULT_PATH_SEPARATOR + "DISPLAY_AUDIT_HISTORY";
	String OMT_AUTO_REMOVE_CANCEL_ORDER = OMT_SECTION + DEFAULT_PATH_SEPARATOR + AUTO_REMOVE_CANCEL_ORDER;

	// tray preferences
	String TRAY_SECTION = "TrayPref";
	String SYSTEM_TRAY_NOTIFICATION = TRAY_SECTION + DEFAULT_PATH_SEPARATOR + "AllowTrayNotifications";
	String TEXTMESSAGE_NOTIFICATION = TRAY_SECTION + DEFAULT_PATH_SEPARATOR + "TextMessageNotification";
	String TEXTMESSAGE_NOTIFICATION_SOUND = TEXTMESSAGE_NOTIFICATION + DEFAULT_PATH_SEPARATOR + "Sound";

    //Message Center Alerts
    String MESSAGE_CENTER_SECTION = "MessageCenter";
    String MESSAGE_CENTER_ALERTS = MESSAGE_CENTER_SECTION + DEFAULT_PATH_SEPARATOR + "MessageCenterAlerts";

    // Account alias feature (SEDL 7237)
	// public static final String ACCOUNT_ALIAS_SECTION = "AcctAliasPref";
	// public static final String CLEARING_SECTION = "ClearingPref";

	// Account link feature (SEDL 7237)
	String LINK_SECTION = "LinkPref";
	// public static final String LINK_FIRM = LINK_SECTION + DEFAULT_PATH_SEPARATOR + "Firm";
	String LINK_ACCOUNT = LINK_SECTION + DEFAULT_PATH_SEPARATOR + "Acct";

    // List of classes that have order entry risk control preferences set
    String ORDER_ENTRY_RISK_CONTROL_CLASS_LIST = "RiskControlClassList";
}
