package com.cboe.infrastructureServices.instrumentationService;
/**
 * This class was generated by a SmartGuide.
 * 
 */
public class InvalidCommPathStatusException extends Exception {

/**
 * InvalidCommPathStatusException constructor comment.
 */
public InvalidCommPathStatusException() {
	super();
}
/**
 * InvalidCommPathStatusException constructor comment.
 * @param s java.lang.String
 */
public InvalidCommPathStatusException(String s) {
	super(s);
}
}
