/* Generated By:JJTree: Do not edit this line. ASTconstraint.java */

package com.cboe.directoryService.parser;

public class ASTconstraint extends SimpleNode {
  public ASTconstraint(int id) {
    super(id);
  }

  public ASTconstraint(DirectoryServiceParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(DirectoryServiceParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
