/* Generated By:JJTree: Do not edit this line. ASTfactor.java */

package com.cboe.directoryService.parser;

public class ASTfactor extends SimpleNode {
  private int flag;

  public ASTfactor(int id) {
    super(id);
  }

  public ASTfactor(DirectoryServiceParser p, int id) {
    super(p, id);
  }
    public void setFlag(int inFlag) {
	flag = inFlag;
    }

    public int getFlag() {
	return flag;
    }

    public boolean equals(Object obj) {
	if(!(obj instanceof ASTfactor)) {
	    return false;
	}
	if (getFlag() != ((ASTfactor)obj).getFlag()) {
	    return false;
	}
	  
	if(jjtGetNumChildren() == ((Node)obj).jjtGetNumChildren()) {
	    for(int i = 0; i < jjtGetNumChildren(); i++) {
		if(jjtGetChild(i).equals(((Node)obj).jjtGetChild(i)) == false) {
		    return false;
		}
	    }
	} else {
	    return false;
	}
	return true;
    }

  
  /** Accept the visitor. **/
  public Object jjtAccept(DirectoryServiceParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
