/* Generated By:JJTree: Do not edit this line. ASTFloat.java */

package com.cboe.directoryService.parser;

public class ASTFloat extends SimpleNode {
  private Double value;
  public ASTFloat(int id) {
    super(id);
  }

  public ASTFloat(DirectoryServiceParser p, int id) {
    super(p, id);
  }
public void setValue(String inValue) {
    value = new Double(inValue);
  }

    public Double getValue() {
	return value;
    }
    public boolean equals(Object obj) {
	if(!(obj instanceof ASTFloat)) {
	    return false;
	}
	if(((Double)value).doubleValue() == ((Double)value).doubleValue()) {
	    return true;
	} else {
	    return false;
	}
    }

  /** Accept the visitor. **/
  public Object jjtAccept(DirectoryServiceParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}

