/* Generated By:JJTree: Do not edit this line. ASTIdent.java */

package com.cboe.directoryService.parser;

public class ASTIdent extends SimpleNode {
  private String value;
  public ASTIdent(int id) {
    super(id);
  }

  public ASTIdent(DirectoryServiceParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(DirectoryServiceParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
  
  /** Set the value. **/
  public void setValue(String n) {
    value = n;
  }
  
  /** return  the value. **/ 
  public String getValue() {
    return value;
  }
  public String toString(String prefix) {
    return prefix + "Identifier: " + value;
  }
}


