/* Generated By:JJTree: Do not edit this line. ASTInteger.java */

package com.cboe.directoryService.parser;

public class ASTInteger extends SimpleNode {
    private Long value;
   
    public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(DirectoryServiceParser p, int id) {
    super(p, id);
  }

public void setValue(String inValue) {
    value = new Long(inValue);
  }

    public Long getValue() {
	return value;
    }
    public boolean equals(Object obj) {
	if(!(obj instanceof ASTInteger)) {
	    return false;
	}
	if(((Long)value).longValue() == ((Long)value).longValue()) {
	    return true;
	} else {
	    return false;
	}
    }

  /** Accept the visitor. **/
  public Object jjtAccept(DirectoryServiceParserVisitor visitor, Object data) throws Exception {
    return visitor.visit(this, data);
  }
}
