/* Generated By:JJTree: Do not edit this line. DirectoryServiceParserVisitor.java */

package com.cboe.directoryService.parser;

public interface DirectoryServiceParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws Exception;
  public Object visit(ASTconstraint node, Object data) throws Exception;
  public Object visit(ASTbool node, Object data) throws Exception;
  public Object visit(ASTbool_compare node, Object data) throws Exception;
  public Object visit(ASTexpr_in node, Object data) throws Exception;
  public Object visit(ASTexpr node, Object data) throws Exception;
  public Object visit(ASTterm node, Object data) throws Exception;
  public Object visit(ASTfactor_not node, Object data) throws Exception;
  public Object visit(ASTfactor node, Object data) throws Exception;
  public Object visit(ASTIdent node, Object data) throws Exception;
  public Object visit(ASTFloat node, Object data) throws Exception;
  public Object visit(ASTInteger node, Object data) throws Exception;
  public Object visit(ASTString node, Object data) throws Exception;
}
