/* Generated By:JJTree&JavaCC: Do not edit this line. DirectoryServiceParserConstants.java */
package com.cboe.directoryService.parser;

public interface DirectoryServiceParserConstants {

  int EOF = 0;
  int NE = 5;
  int EQ = 6;
  int LT = 7;
  int LE = 8;
  int GT = 9;
  int GE = 10;
  int IN = 11;
  int OR = 12;
  int AND = 13;
  int NOT = 14;
  int TRUE = 15;
  int FALSE = 16;
  int EXIST = 17;
  int PLUS = 18;
  int MINUS = 19;
  int MULT = 20;
  int DIV = 21;
  int TWIDDLE = 22;
  int LPAREN = 23;
  int RPAREN = 24;
  int DOT = 25;
  int BACKSLASH = 26;
  int LENGTH = 27;
  int DTYPE = 28;
  int TYPEID = 29;
  int REPOSID = 30;
  int SUBSCRIPT = 31;
  int ID = 32;
  int INTEGER = 33;
  int FLOAT = 34;
  int MANTISSA = 35;
  int EXPONENT = 36;
  int STRING = 37;
  int SPECIAL = 38;
  int OTHER = 39;
  int ALPHA = 40;
  int DIGITS = 41;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"!=\"",
    "\"==\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"in\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"exist\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"\\\\\"",
    "\"_length\"",
    "\"_d\"",
    "\"_type_id\"",
    "\"_repos_id\"",
    "<SUBSCRIPT>",
    "<ID>",
    "<INTEGER>",
    "<FLOAT>",
    "<MANTISSA>",
    "<EXPONENT>",
    "<STRING>",
    "<SPECIAL>",
    "<OTHER>",
    "<ALPHA>",
    "<DIGITS>",
  };

}
