// -----------------------------------------------------------------------------------
// Source file: BusinessModelCollectionEventImpl.java
//
// PACKAGE: com.cboe.presentation.common.businessModels;
//
// -----------------------------------------------------------------------------------
// Copyright (c) 2001 The Chicago Board Options Exchange. All Rights Reserved.
// -----------------------------------------------------------------------------------
package com.cboe.presentation.common.businessModels;

import java.util.EventObject;

import com.cboe.interfaces.presentation.common.businessModels.BusinessModel;
import com.cboe.interfaces.presentation.common.businessModels.BusinessModelCollectionEvent;

/**
 * Special event that can be generated by the BusinessModelCollection object
 */
public class BusinessModelCollectionEventImpl extends EventObject implements BusinessModelCollectionEvent
{
    private BusinessModel element = null;

    /**
     * Default Constructor
     * @param source of event
     */
    private BusinessModelCollectionEventImpl(Object source)
    {
        super(source);
    }

    /**
     * Constructor
     * @param source of event
     * @param business model for the event
     */
    public BusinessModelCollectionEventImpl(Object source, BusinessModel model)
    {
        super(source);
        this.element = model;
    }

    /**
     * Gets the model for the event
     * @return BusinessModel event occured for.
     */
    public BusinessModel getElement()
    {
        return this.element;
    }

    /**
     * Returns the BusinessModelCollection on which event occurred.
     * @return Object event occured on.
     */
    public Object getSource()
    {
        return super.getSource();
    }

    /**
     * Returns a String representation of this BusinessModelCollectionEvent.
     * @return String representation of this BusinessModelCollectionEvent.
     */
    public String toString()
    {
        return super.toString();
    }

}