package com.cboe.client.util.collections;

/**
 * IntIntKeyValuePolicy.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyValuePolicy.java (KEY_TYPE=int, VALUE_TYPE=int)
 *
 */

public class IntIntKeyValuePolicy implements IntIntKeyValuePolicyIF
{
    public boolean canInsert(int key, int newValue)
    {
        return true;
    }
    public boolean canUpdate(int key, int newValue, int oldValue)
    {
        return true;
    }
    public boolean canRemove(int key, int oldValue)
    {
        return true;
    }
}

