package com.cboe.client.util.collections;

/**
 * IntKeyPolicyIF.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyPolicyIF.java (KEY_TYPE=int)
 *
 */

public interface IntKeyPolicyIF
{
    public boolean canInsert(int key);
    public boolean canRemove(int key);
}

