package com.cboe.client.util.collections;

/**
 * IntLongKeyValuePolicy.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyValuePolicy.java (KEY_TYPE=int, VALUE_TYPE=long)
 *
 */

public class IntLongKeyValuePolicy implements IntLongKeyValuePolicyIF
{
    public boolean canInsert(int key, long newValue)
    {
        return true;
    }
    public boolean canUpdate(int key, long newValue, long oldValue)
    {
        return true;
    }
    public boolean canRemove(int key, long oldValue)
    {
        return true;
    }
}

