package com.cboe.client.util.collections;

/**
 * IntLongArrayHolderIF.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYArrayHolderIF.java (KEY_TYPE=int, VALUE_TYPE=long)
 *
 */

import com.cboe.client.util.*;

public interface IntLongArrayHolderIF extends HasSizeIF
{
    public int size();
    public boolean isEmpty();
    public int capacity();
    public int ensureCapacity(int capacity);
    public int[] keys();
    public int[] getKeys();
    public long[] values();
    public long[] getValues();
    public void add(int key, long value);
    public int getKey(int index);
    public long getValue(int index);
    public boolean containsKey(int key);
    public boolean containsValue(long value);
    public IntLongArrayHolderIF clear();
    public IntLongVisitorIF acceptVisitor(IntLongVisitorIF visitor);
}

