package com.cboe.client.util.collections;

/**
 * IntLongKeyValuePolicyIF.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyValuePolicyIF.java (KEY_TYPE=int, VALUE_TYPE=long)
 *
 */

public interface IntLongKeyValuePolicyIF
{
    public boolean canInsert(int key, long newValue);
    public boolean canUpdate(int key, long newValue, long oldValue);
    public boolean canRemove(int key, long oldValue);
}

