package com.cboe.client.util.collections;

/**
 * IntObjectKeyValuePolicy.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyValuePolicy.java (KEY_TYPE=int, VALUE_TYPE=Object)
 *
 */

public class IntObjectKeyValuePolicy implements IntObjectKeyValuePolicyIF
{
    public boolean canInsert(int key, Object newValue)
    {
        return true;
    }
    public boolean canUpdate(int key, Object newValue, Object oldValue)
    {
        return true;
    }
    public boolean canRemove(int key, Object oldValue)
    {
        return true;
    }
}

