package com.cboe.client.util.collections;

/**
 * IntObjectVisitorIF
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYZVisitor.java (KEY_TYPE=int, VALUE_TYPE=Object)
 *
 */

public interface IntObjectVisitorIF
{
    public static final int ABORT    = 0;
    public static final int CONTINUE = 1;
    public static final int SKIP     = 2;

    public int visit(int key, Object value);
}

