package com.cboe.client.util.collections;

/**
 * IntObjectKeyValuePolicyIF.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyValuePolicyIF.java (KEY_TYPE=int, VALUE_TYPE=Object)
 *
 */

public interface IntObjectKeyValuePolicyIF
{
    public boolean canInsert(int key, Object newValue);
    public boolean canUpdate(int key, Object newValue, Object oldValue);
    public boolean canRemove(int key, Object oldValue);
}

