package com.cboe.client.util.collections;

/**
 * IntStringMap.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYMap.java (KEY_TYPE=int, VALUE_TYPE=String)
 *
 */

import com.cboe.client.util.*;

public class IntStringMap implements HasSizeIF
{
    protected int[][] keys;
    protected String[][] values;
    protected int[]        numberKeys;
    protected int          tableHighestIndex;
    protected volatile int size;

    public String ValueNotFound;

    public static final int VALUE_ADDED     = -12345;
    public static final int VALUE_REPLACED  = -23456;
    public static final int VALUE_UNCHANGED = -34567;

    public static final int DEFAULT_INITIAL_CAPACITY       = 256;
    public static final int DEFAULT_ENTRY_LIST_CAPACITY    = 16;
    public static final int MAXIMUM_CAPACITY               = 1024 * 16;

    public static final IntStringMap unsynchronizedMap()             {return new IntStringMap();}
    public static final IntStringMap unsynchronizedMap(int capacity) {return new IntStringMap(capacity);}
    public static final IntStringMap synchronizedMap()               {return new IntStringMapMT();}
    public static final IntStringMap synchronizedMap(int capacity)   {return new IntStringMapMT(capacity);}

    public static class IntStringMapMT extends IntStringMap
    {
        public IntStringMapMT()
        {
            super();
        }
        public IntStringMapMT(int capacity)
        {
            super(capacity);
        }
        public synchronized boolean containsKey(int key)
        {
            return super.containsKey(key);
        }
        public synchronized boolean containsValue(String value)
        {
            return super.containsValue(value);
        }
        public synchronized void getKeysForValue(String value, IntArrayHolderIF arrayHolder)
        {
            super.getKeysForValue(value, arrayHolder);
        }
        public synchronized String getValueForKey(int key)
        {
            return super.getValueForKey(key);
        }
        public synchronized int putKeyValue(int key, String value)
        {
            return super.putKeyValue(key, value);
        }
        public synchronized int putKeyValue(int key, String value, IntObjectKeyValuePolicyIF policy)
        {
            return super.putKeyValue(key, value, policy);
        }
        public synchronized String removeKey(int key)
        {
            return super.removeKey(key);
        }
        public synchronized String removeKey(int key, IntObjectKeyValuePolicyIF policy)
        {
            return super.removeKey(key, policy);
        }
        public synchronized IntObjectVisitorIF acceptVisitor(IntObjectVisitorIF visitor)
        {
            return super.acceptVisitor(visitor);
        }
        public synchronized IntStringMap clear()
        {
            return super.clear();
        }
        public synchronized IntStringMap clear(IntStringArrayHolderIF arrayHolder)
        {
            return super.clear(arrayHolder);
        }
    };

    public IntStringMap()
    {
        this(DEFAULT_INITIAL_CAPACITY);
    }

    public IntStringMap(int capacity)
    {
        if (capacity < 2)
        {
            capacity = DEFAULT_INITIAL_CAPACITY;
        }
        else if (capacity > MAXIMUM_CAPACITY)
        {
            capacity = MAXIMUM_CAPACITY;
        }
        else
        {
            capacity = IntegerHelper.higherPowerOf2(capacity);
        }

        keys              = new int[capacity][];
        values            = new String[capacity][];
        numberKeys        = new int[capacity];
        tableHighestIndex = capacity - 1;
    }

    public String getValueNotFound()
    {
        return ValueNotFound;
    }

    public IntStringMap setValueNotFound(String ValueNotFound)
    {
        this.ValueNotFound = ValueNotFound;

        return this;
    }

    public int size()
    {
        return size;
    }

    public boolean isEmpty()
    {
        return size == 0;
    }

    public boolean containsKey(int key)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (numberKeys[bucketIndex] > 0)
        {
            return CollectionHelper.binarySearch(keys[bucketIndex], key, numberKeys[bucketIndex]) >= 0;
        }

        return false;
    }

    public boolean containsValue(String value)
    {
        int      bucketSize;
        int      keyIndex;
        String[] local_values;

        for (int bucketIndex = keys.length; --bucketIndex >= 0; )
        {
            bucketSize = numberKeys[bucketIndex];

            if (bucketSize > 0)
            {
                local_values = values[bucketIndex];

                for (keyIndex = 0; keyIndex < bucketSize; keyIndex++)
                {
                    if (value == local_values[keyIndex] || value.compareTo(local_values[keyIndex]) == 0)
                    {
                        return true;
                    }
                }
            }
        }

        return false;
    }

    public void getKeysForValue(String value, IntArrayHolderIF arrayHolder)
    {
        int      bucketSize;
        int      keyIndex;
        String[] local_values;

        for (int bucketIndex = keys.length; --bucketIndex >= 0; )
        {
            bucketSize = numberKeys[bucketIndex];

            if (bucketSize > 0)
            {
                local_values = values[bucketIndex];

                for (keyIndex = 0; keyIndex < bucketSize; keyIndex++)
                {
                    if (value == local_values[keyIndex] || value.compareTo(local_values[keyIndex]) == 0)
                    {
                        arrayHolder.add(keys[bucketIndex][keyIndex]);
                    }
                }
            }
        }
    }

    public String getValueForKey(int key)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (numberKeys[bucketIndex] > 0)
        {
            int keyIndex = CollectionHelper.binarySearch(keys[bucketIndex], key, numberKeys[bucketIndex]);
            if (keyIndex >= 0)
            {
                return values[bucketIndex][keyIndex];
            }
        }

        return ValueNotFound;
    }

    public void getData(IntStringArrayHolderIF arrayHolder)
    {
        int             bucketSize;
        int             keyIndex;
        int[]   local_keys;
        String[] local_values;

        for (int bucketIndex = 0; bucketIndex < keys.length; bucketIndex++)
        {
            bucketSize = numberKeys[bucketIndex];

            if (bucketSize > 0)
            {
                local_values = values[bucketIndex];
                local_keys   = keys[bucketIndex];

                for (keyIndex = 0; keyIndex < bucketSize; keyIndex++)
                {
                    arrayHolder.add(local_keys[keyIndex], local_values[keyIndex]);
                }
            }
        }
    }

    public int putKeyValue(int key, String value)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (keys[bucketIndex] == null)
        {
            keys[bucketIndex]       = new int[DEFAULT_ENTRY_LIST_CAPACITY];
            values[bucketIndex]     = new String[DEFAULT_ENTRY_LIST_CAPACITY];
            keys[bucketIndex][0]    = key;
            values[bucketIndex][0]  = value;
            numberKeys[bucketIndex] = 1;
            size++;

            return VALUE_ADDED;
        }

        int keyIndex;
        int[] local_keys = keys[bucketIndex];
        String[] local_values = values[bucketIndex];
        int local_numberKeys = numberKeys[bucketIndex];

        keyIndex = CollectionHelper.binarySearch(local_keys, key, local_numberKeys);
        if (keyIndex >= 0)
        {
            local_values[keyIndex] = value;
            return VALUE_REPLACED;
	    }

        // if we got here, this is completely new

        keyIndex = CollectionHelper.normalizeBinarySearchPosition(keyIndex);
        if (local_numberKeys >= local_keys.length) // need to expand
        {
            if (keyIndex == local_numberKeys) // if at end, then just arrayclone, and append later
            {
                keys[bucketIndex]   = CollectionHelper.arrayclone(local_keys,   0, local_keys.length, local_keys.length << 1);
                values[bucketIndex] = CollectionHelper.arrayclone(local_values, 0, local_keys.length, local_keys.length << 1);
            }
            else
            {
                keys[bucketIndex]   = CollectionHelper.arraycloneExpandGap(local_keys,   0, local_keys.length, local_keys.length << 1, keyIndex, 1);
                values[bucketIndex] = CollectionHelper.arraycloneExpandGap(local_values, 0, local_keys.length, local_keys.length << 1, keyIndex, 1);
            }
        }
        else
        {
            if (keyIndex < local_numberKeys)
            {
                System.arraycopy(local_values, keyIndex, local_values, keyIndex + 1, local_numberKeys - keyIndex);
                System.arraycopy(local_keys,   keyIndex, local_keys,   keyIndex + 1, local_numberKeys - keyIndex);
            }
        }

        keys[bucketIndex][keyIndex]   = key;
        values[bucketIndex][keyIndex] = value;

        numberKeys[bucketIndex]++;
        size++;

        return VALUE_ADDED;
    }

    public int putKeyValue(int key, String value, IntObjectKeyValuePolicyIF policy)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (keys[bucketIndex] == null)
        {
            if (!policy.canInsert(key, value))
            {
                return VALUE_UNCHANGED;
            }

            keys[bucketIndex]       = new int[DEFAULT_ENTRY_LIST_CAPACITY];
            values[bucketIndex]     = new String[DEFAULT_ENTRY_LIST_CAPACITY];
            keys[bucketIndex][0]    = key;
            values[bucketIndex][0]  = value;
            numberKeys[bucketIndex] = 1;
            size++;

            return VALUE_ADDED;
        }

        int keyIndex;
        int[] local_keys = keys[bucketIndex];
        String[] local_values = values[bucketIndex];
        int local_numberKeys = numberKeys[bucketIndex];

        keyIndex = CollectionHelper.binarySearch(local_keys, key, local_numberKeys);
        if (keyIndex >= 0)
        {
            if (policy.canUpdate(keys[bucketIndex][keyIndex], values[bucketIndex][keyIndex], value))
            {
                local_values[keyIndex] = value;
                return VALUE_REPLACED;
            }

            return VALUE_UNCHANGED;
	    }

        // if we got here, this is completely new

        if (!policy.canInsert(key, value))
        {
            return VALUE_UNCHANGED;
        }

        keyIndex = CollectionHelper.normalizeBinarySearchPosition(keyIndex);
        if (local_numberKeys >= local_keys.length) // need to expand
        {
            if (keyIndex == local_numberKeys) // if at end, then just arrayclone, and append later
            {
                keys[bucketIndex]   = CollectionHelper.arrayclone(local_keys,   0, local_keys.length, local_keys.length << 1);
                values[bucketIndex] = CollectionHelper.arrayclone(local_values, 0, local_keys.length, local_keys.length << 1);
            }
            else
            {
                keys[bucketIndex]   = CollectionHelper.arraycloneExpandGap(local_keys,   0, local_keys.length, local_keys.length << 1, keyIndex, 1);
                values[bucketIndex] = CollectionHelper.arraycloneExpandGap(local_values, 0, local_keys.length, local_keys.length << 1, keyIndex, 1);
            }
        }
        else
        {
            if (keyIndex < local_numberKeys)
            {
                System.arraycopy(local_values, keyIndex, local_values, keyIndex + 1, local_numberKeys - keyIndex);
                System.arraycopy(local_keys,   keyIndex, local_keys,   keyIndex + 1, local_numberKeys - keyIndex);
            }
        }

        keys[bucketIndex][keyIndex]   = key;
        values[bucketIndex][keyIndex] = value;

        numberKeys[bucketIndex]++;
        size++;

        return VALUE_ADDED;
    }

    public String removeKey(int key)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (numberKeys[bucketIndex] > 0)
        {
            int keyIndex;
            int[] local_keys = keys[bucketIndex];
            String[] local_values = values[bucketIndex];
            int local_numberKeys = numberKeys[bucketIndex];

            keyIndex = CollectionHelper.binarySearch(local_keys, key, local_numberKeys);
            if (keyIndex >= 0)
            {
                String oldValue = local_values[keyIndex];

                int highest_index = local_values.length - 1;

                if (keyIndex < highest_index)
                {
                    System.arraycopy(local_values, keyIndex + 1, local_values, keyIndex, highest_index - keyIndex);
                    System.arraycopy(local_keys,   keyIndex + 1, local_keys,   keyIndex, highest_index - keyIndex);
                }

                local_keys[highest_index]   = 0;
                local_values[highest_index] = null;

                numberKeys[bucketIndex]--;
                size--;

                return oldValue;
	        }
        }

        return ValueNotFound;
    }

    public String removeKey(int key, IntObjectKeyValuePolicyIF policy)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (numberKeys[bucketIndex] > 0)
        {
            int keyIndex;
            int[] local_keys = keys[bucketIndex];
            String[] local_values = values[bucketIndex];
            int local_numberKeys = numberKeys[bucketIndex];

            keyIndex = CollectionHelper.binarySearch(local_keys, key, local_numberKeys);
            if (keyIndex >= 0)
            {
                String oldValue = local_values[keyIndex];

                if (!policy.canRemove(key, oldValue))
                {
                    return ValueNotFound;
                }

                int highest_index = local_values.length - 1;

                if (keyIndex < highest_index)
                {
                    System.arraycopy(local_values, keyIndex + 1, local_values, keyIndex, highest_index - keyIndex);
                    System.arraycopy(local_keys,   keyIndex + 1, local_keys,   keyIndex, highest_index - keyIndex);
                }

                local_keys[highest_index]   = 0;
                local_values[highest_index] = null;

                numberKeys[bucketIndex]--;
                size--;

                return oldValue;
	        }
        }

        return ValueNotFound;
    }

    public IntObjectVisitorIF acceptVisitor(IntObjectVisitorIF visitor)
    {
        int             bucketSize;
        int             keyIndex;
        int             rc;
        int[]   local_keys;
        String[] local_values;

        for (int bucketIndex = 0; bucketIndex < keys.length; bucketIndex++)
        {
            bucketSize = numberKeys[bucketIndex];

            local_keys = keys[bucketIndex];

            if (bucketSize > 0)
            {
                local_values = values[bucketIndex];

                for (keyIndex = 0; keyIndex < bucketSize; keyIndex++)
                {
                    rc = visitor.visit(local_keys[keyIndex], local_values[keyIndex]);

                    if (rc == IntObjectVisitorIF.CONTINUE)
                    {
                        continue;
                    }

                    if (rc == IntObjectVisitorIF.ABORT)
                    {
                         return visitor;
                    }
                }
            }
        }

        return visitor;
    }

    public IntStringMap clear()
    {
        for (int bucketIndex = keys.length; --bucketIndex >= 0; )
        {
            keys[bucketIndex]   = null;
            values[bucketIndex] = null;
            numberKeys[bucketIndex]  = 0;
        }

        size = 0;

        return this;
    }

    public IntStringMap clear(IntStringArrayHolderIF arrayHolder)
    {
        getData(arrayHolder);

        for (int bucketIndex = keys.length; --bucketIndex >= 0; )
        {
            keys[bucketIndex]   = null;
            values[bucketIndex] = null;
            numberKeys[bucketIndex]  = 0;
        }

        size = 0;

        return this;
    }
}

