package com.cboe.client.util.collections;

/**
 * IntStringArrayHolderIF.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYArrayHolderIF.java (KEY_TYPE=int, VALUE_TYPE=String)
 *
 */

import com.cboe.client.util.*;

public interface IntStringArrayHolderIF extends HasSizeIF
{
    public int size();
    public boolean isEmpty();
    public int capacity();
    public int ensureCapacity(int capacity);
    public int[] keys();
    public int[] getKeys();
    public String[] values();
    public String[] getValues();
    public void add(int key, String value);
    public int getKey(int index);
    public String getValue(int index);
    public boolean containsKey(int key);
    public boolean containsValue(String value);
    public IntStringArrayHolderIF clear();
    public IntObjectVisitorIF acceptVisitor(IntObjectVisitorIF visitor);
}

