package com.cboe.client.util.collections;

/**
 * LongArrayHolder.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XArrayHolder.java (KEY_TYPE=long)
 *
 */

import com.cboe.client.util.*;

public class LongArrayHolder implements LongArrayHolderIF
{
    public long[] keys;
    public int   size;

    public static final LongArrayHolderIF EmptyArrayHolder = new LongArrayHolder()
    {
        public void add(long key) {}
        public void add(long[] keyArray) {}
        public void add(long[] keyArray, int offset, int length) {}
    };

    public LongArrayHolder()
    {
        this(0);
    }

    public LongArrayHolder(int capacity)
    {
        keys = new long[capacity];
    }

    public int size()
    {
        return size;
    }

    public boolean isEmpty()
    {
        return size == 0;
    }

    public int capacity()
    {
        return keys.length;
    }

    public int ensureCapacity(int capacity)
    {
        if (keys.length < capacity)
        {
            keys = CollectionHelper.arrayclone(keys, 0, keys.length, capacity);
        }

        return keys.length;
    }

    public long[] keys()
    {
        return keys;
    }

    public long[] getKeys()
    {
        return CollectionHelper.arrayclone(keys, size);
    }

    public void add(long key)
    {
        int newSize = size + 1;

        if (newSize >= keys.length)
        {
            keys = CollectionHelper.arrayclone(keys, 0, keys.length, newSize);
        }

        keys[size] = key;

        size = newSize;
    }

    public void add(long[] keyArray)
    {
        int newSize = size + keyArray.length;

        if (newSize >= keys.length)
        {
            keys = CollectionHelper.arrayclone(keys, 0, keys.length, newSize);
        }

        System.arraycopy(keyArray, 0, keys, size, keyArray.length);

        size = newSize;
    }

    public void add(long[] keyArray, int offset, int length)
    {
        int newSize = size + length;

        if (newSize >= keys.length)
        {
            keys = CollectionHelper.arrayclone(keys, 0, keys.length, newSize);
        }

        System.arraycopy(keyArray, offset, keys, size, length);

        size = newSize;
    }

    public long getKey(int index)
    {
        if (index < size)
        {
            return keys[index];
        }

        return IntegerHelper.INVALID_VALUE;
    }

    public boolean containsKey(long object)
    {
        for (int i = 0; i < size; i++)
        {
            if (keys[i] == object)
            {
                return true;
            }
        }

        return false;
    }

    public LongVisitorIF acceptVisitor(LongVisitorIF visitor)
    {
        for (int i = 0; i < size; i++)
        {
            visitor.visit(keys[i]);
        }

        return visitor;
    }

    public LongArrayHolderIF clear()
    {

        size = 0;

        return this;
    }
}

