package com.cboe.client.util.collections;

/**
 * LongReferenceCountMap.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XReferenceCountMap.java (KEY_TYPE=long)
 *
 */

import com.cboe.client.util.*;

public class LongReferenceCountMap implements HasSizeIF
{
    protected long[][] keys;
    protected int[][] values;
    protected int[]        sizes;
    protected int          tableHighestIndex;
    protected volatile int size;

    public static final int DEFAULT_INITIAL_CAPACITY       = 256;
    public static final int DEFAULT_ENTRY_LIST_CAPACITY    = 16;
    public static final int MAXIMUM_CAPACITY               = 1024 * 16;

    public static final LongReferenceCountMap unsynchronizedMap()             {return new LongReferenceCountMap();}
    public static final LongReferenceCountMap unsynchronizedMap(int capacity) {return new LongReferenceCountMap(capacity);}
    public static final LongReferenceCountMap synchronizedMap()               {return new LongReferenceCountMapMT();}
    public static final LongReferenceCountMap synchronizedMap(int capacity)   {return new LongReferenceCountMapMT(capacity);}

    public static class LongReferenceCountMapMT extends LongReferenceCountMap
    {
        public LongReferenceCountMapMT()
        {
            super();
        }
        public LongReferenceCountMapMT(int capacity)
        {
            super(capacity);
        }
        public LongReferenceCountMapMT(LongReferenceCountMap map)
        {
            super(map);
        }
        public synchronized boolean containsKey(long key)
        {
            return super.containsKey(key);
        }
        public synchronized int getValueForKey(long key)
        {
            return super.getValueForKey(key);
        }
        public synchronized void incKeyValue(long key, int value)
        {
            super.incKeyValue(key, value);
        }
        public synchronized void decKeyValuePositive(long key, int value)
        {
            super.decKeyValuePositive(key, value);
        }
        public synchronized void getData(LongIntArrayHolderIF arrayHolder)
        {
            super.getData(arrayHolder);
        }
        public synchronized void putKeyValue(long key, int value)
        {
            super.putKeyValue(key, value);
        }
        public synchronized int removeKey(long key)
        {
            return super.removeKey(key);
        }
        public synchronized LongIntVisitorIF acceptVisitor(LongIntVisitorIF visitor)
        {
            return super.acceptVisitor(visitor);
        }
        public synchronized LongReferenceCountMap clear()
        {
            return super.clear();
        }
        public synchronized LongReferenceCountMap clear(LongIntArrayHolderIF arrayHolder)
        {
            return super.clear(arrayHolder);
        }
    };

    public LongReferenceCountMap()
    {
        this(DEFAULT_INITIAL_CAPACITY);
    }

    public LongReferenceCountMap(int capacity)
    {
        if (capacity < 2)
        {
            capacity = DEFAULT_INITIAL_CAPACITY;
        }
        else if (capacity > MAXIMUM_CAPACITY)
        {
            capacity = MAXIMUM_CAPACITY;
        }
        else
        {
            capacity = IntegerHelper.higherPowerOf2(capacity);
        }

        keys              = new long[capacity][];
        values            = new int[capacity][];
        sizes             = new int[capacity];
        tableHighestIndex = capacity - 1;
    }

    public LongReferenceCountMap(LongReferenceCountMap map)
    {
        synchronized(map)
        {
            sizes             = CollectionHelper.arrayclone(map.sizes);
            keys              = CollectionHelper.arraycloneDimensions(map.keys);
            values            = CollectionHelper.arraycloneDimensions(map.values);
            size              = map.size;
            tableHighestIndex = map.tableHighestIndex;
        }
    }

    public int size()
    {
        return size;
    }

    public boolean isEmpty()
    {
        return size == 0;
    }

    public boolean containsKey(long key)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (sizes[bucketIndex] > 0)
        {
            return CollectionHelper.binarySearch(keys[bucketIndex], key, sizes[bucketIndex]) >= 0;
        }

        return false;
    }

    public int getValueForKey(long key)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (sizes[bucketIndex] > 0)
        {
            int keyIndex = CollectionHelper.binarySearch(keys[bucketIndex], key, sizes[bucketIndex]);
            if (keyIndex >= 0)
            {
                return values[bucketIndex][keyIndex];
            }
        }

        return 0;
    }

    public void incKeyValue(long key)
    {
        incKeyValue(key, 1);
    }

    public void incKeyValue(long key, int value)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (keys[bucketIndex] == null)
        {
            keys[bucketIndex]      = new long[DEFAULT_ENTRY_LIST_CAPACITY];
            values[bucketIndex]    = new int[DEFAULT_ENTRY_LIST_CAPACITY];
            keys[bucketIndex][0]   = key;
            values[bucketIndex][0] = value;
            sizes[bucketIndex]     = 1;
            size++;

            return;
        }

        int keyIndex;
        long[] local_keys = keys[bucketIndex];
        int[] local_values = values[bucketIndex];
        int local_size = sizes[bucketIndex];

        keyIndex = CollectionHelper.binarySearch(local_keys, key, local_size);
        if (keyIndex >= 0)
        {
            values[bucketIndex][keyIndex] += value;
            return;
	    }

        // if we got here, this is completely new

        keyIndex = CollectionHelper.normalizeBinarySearchPosition(keyIndex);
        if (local_size >= local_keys.length) // need to expand
        {
            if (keyIndex == local_size) // if at end, then just arrayclone, and append later
            {
                keys[bucketIndex]   = CollectionHelper.arrayclone(local_keys,   0, local_keys.length, local_keys.length << 1);
                values[bucketIndex] = CollectionHelper.arrayclone(local_values, 0, local_keys.length, local_keys.length << 1);
            }
            else
            {
                keys[bucketIndex]   = CollectionHelper.arraycloneExpandGap(local_keys,   0, local_keys.length, local_keys.length << 1, keyIndex, 1);
                values[bucketIndex] = CollectionHelper.arraycloneExpandGap(local_values, 0, local_keys.length, local_keys.length << 1, keyIndex, 1);
            }
        }
        else
        {
            if (keyIndex < local_size)
            {
                System.arraycopy(local_values, keyIndex, local_values, keyIndex + 1, local_size - keyIndex);
                System.arraycopy(local_keys,   keyIndex, local_keys,   keyIndex + 1, local_size - keyIndex);
            }
        }

        keys[bucketIndex][keyIndex]   = key;
        values[bucketIndex][keyIndex] = value;

        sizes[bucketIndex]++;
        size++;
    }

    public void decKeyValue(long key)
    {
        incKeyValue(key, -1);
    }

    public void decKeyValue(long key, int value)
    {
        incKeyValue(key, -value);
    }

    public void decKeyValuePositive(long key)
    {
        decKeyValuePositive(key, 1);
    }

    public void decKeyValuePositive(long key, int value)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (keys[bucketIndex] == null)
        {
            keys[bucketIndex]      = new long[DEFAULT_ENTRY_LIST_CAPACITY];
            values[bucketIndex]    = new int[DEFAULT_ENTRY_LIST_CAPACITY];
            keys[bucketIndex][0]   = key;
            values[bucketIndex][0] = 0;
            sizes[bucketIndex]     = 1;
            size++;

            return;
        }

        int keyIndex;
        long[] local_keys = keys[bucketIndex];
        int[] local_values = values[bucketIndex];
        int local_size = sizes[bucketIndex];

        keyIndex = CollectionHelper.binarySearch(local_keys, key, local_size);
        if (keyIndex >= 0)
        {
            values[bucketIndex][keyIndex] -= value;
            if (values[bucketIndex][keyIndex] < 0)
            {
                values[bucketIndex][keyIndex] = 0;
            }
            return;
	    }

        // if we got here, this is completely new

        keyIndex = CollectionHelper.normalizeBinarySearchPosition(keyIndex);
        if (local_size >= local_keys.length) // need to expand
        {
            if (keyIndex == local_size) // if at end, then just arrayclone, and append later
            {
                keys[bucketIndex]   = CollectionHelper.arrayclone(local_keys,   0, local_keys.length, local_keys.length << 1);
                values[bucketIndex] = CollectionHelper.arrayclone(local_values, 0, local_keys.length, local_keys.length << 1);
            }
            else
            {
                keys[bucketIndex]   = CollectionHelper.arraycloneExpandGap(local_keys,   0, local_keys.length, local_keys.length << 1, keyIndex, 1);
                values[bucketIndex] = CollectionHelper.arraycloneExpandGap(local_values, 0, local_keys.length, local_keys.length << 1, keyIndex, 1);
            }
        }
        else
        {
            if (keyIndex < local_size)
            {
                System.arraycopy(local_values, keyIndex, local_values, keyIndex + 1, local_size - keyIndex);
                System.arraycopy(local_keys,   keyIndex, local_keys,   keyIndex + 1, local_size - keyIndex);
            }
        }

        keys[bucketIndex][keyIndex]   = key;
        values[bucketIndex][keyIndex] = 0;

        sizes[bucketIndex]++;
        size++;
    }

    public void getData(LongIntArrayHolderIF arrayHolder)
    {
        int             bucketSize;
        int             keyIndex;
        long[]   local_keys;
        int[] local_values;

        for (int bucketIndex = 0; bucketIndex < keys.length; bucketIndex++)
        {
            bucketSize = sizes[bucketIndex];

            if (bucketSize > 0)
            {
                local_values = values[bucketIndex];
                local_keys   = keys[bucketIndex];

                for (keyIndex = 0; keyIndex < bucketSize; keyIndex++)
                {
                    arrayHolder.add(local_keys[keyIndex], local_values[keyIndex]);
                }
            }
        }
    }

    public void putKeyValue(long key, int value)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (keys[bucketIndex] == null)
        {
            keys[bucketIndex]      = new long[DEFAULT_ENTRY_LIST_CAPACITY];
            values[bucketIndex]    = new int[DEFAULT_ENTRY_LIST_CAPACITY];
            keys[bucketIndex][0]   = key;
            values[bucketIndex][0] = value;
            sizes[bucketIndex]     = 1;
            size++;

            return;
        }

        int keyIndex;
        long[] local_keys = keys[bucketIndex];
        int[] local_values = values[bucketIndex];
        int local_size = sizes[bucketIndex];

        keyIndex = CollectionHelper.binarySearch(local_keys, key, local_size);
        if (keyIndex >= 0)
        {
            values[bucketIndex][keyIndex] = value;
            return;
	    }

        // if we got here, this is completely new

        keyIndex = CollectionHelper.normalizeBinarySearchPosition(keyIndex);
        if (local_size >= local_keys.length) // need to expand
        {
            if (keyIndex == local_size) // if at end, then just arrayclone, and append later
            {
                keys[bucketIndex]   = CollectionHelper.arrayclone(local_keys,   0, local_keys.length, local_keys.length << 1);
                values[bucketIndex] = CollectionHelper.arrayclone(local_values, 0, local_keys.length, local_keys.length << 1);
            }
            else
            {
                keys[bucketIndex]   = CollectionHelper.arraycloneExpandGap(local_keys,   0, local_keys.length, local_keys.length << 1, keyIndex, 1);
                values[bucketIndex] = CollectionHelper.arraycloneExpandGap(local_values, 0, local_keys.length, local_keys.length << 1, keyIndex, 1);
            }
        }
        else
        {
            if (keyIndex < local_size)
            {
                System.arraycopy(local_values, keyIndex, local_values, keyIndex + 1, local_size - keyIndex);
                System.arraycopy(local_keys,   keyIndex, local_keys,   keyIndex + 1, local_size - keyIndex);
            }
        }

        keys[bucketIndex][keyIndex]   = key;
        values[bucketIndex][keyIndex] = value;

        sizes[bucketIndex]++;
        size++;
    }

    public int removeKey(long key)
    {
        int bucketIndex = (int) (key & tableHighestIndex);

        if (sizes[bucketIndex] > 0)
        {
            int keyIndex;
            long[] local_keys = keys[bucketIndex];
            int[] local_values = values[bucketIndex];
            int local_size = sizes[bucketIndex];

            keyIndex = CollectionHelper.binarySearch(local_keys, key, local_size);
            if (keyIndex >= 0)
            {
                int oldValue = local_values[keyIndex];

                int highest_index = local_values.length - 1;

                if (keyIndex < highest_index)
                {
                    System.arraycopy(local_values, keyIndex + 1, local_values, keyIndex, highest_index - keyIndex);
                    System.arraycopy(local_keys,   keyIndex + 1, local_keys,   keyIndex, highest_index - keyIndex);
                }

                local_keys[highest_index]   = 0;
                local_values[highest_index] = 0;

                sizes[bucketIndex]--;
                size--;

                return oldValue;
	        }
        }

        return 0;
    }

    public LongIntVisitorIF acceptVisitor(LongIntVisitorIF visitor)
    {
        int             bucketSize;
        int             keyIndex;
        int             rc;
        long[]   local_keys;
        int[] local_values;

        for (int bucketIndex = 0; bucketIndex < keys.length; bucketIndex++)
        {
            bucketSize = sizes[bucketIndex];

            local_keys = keys[bucketIndex];

            if (bucketSize > 0)
            {
                local_values = values[bucketIndex];

                for (keyIndex = 0; keyIndex < bucketSize; keyIndex++)
                {
                    rc = visitor.visit(local_keys[keyIndex], local_values[keyIndex]);

                    if (rc == LongIntVisitorIF.CONTINUE)
                    {
                        continue;
                    }

                    if (rc == LongIntVisitorIF.ABORT)
                    {
                         return visitor;
                    }
                }
            }
        }

        return visitor;
    }

    public LongReferenceCountMap clear()
    {
        for (int bucketIndex = keys.length; --bucketIndex >= 0; )
        {
            keys[bucketIndex]   = null;
            values[bucketIndex] = null;
            sizes[bucketIndex]  = 0;
        }

        size = 0;

        return this;
    }

    public LongReferenceCountMap clear(LongIntArrayHolderIF arrayHolder)
    {
        getData(arrayHolder);

        for (int bucketIndex = keys.length; --bucketIndex >= 0; )
        {
            keys[bucketIndex]   = null;
            values[bucketIndex] = null;
            sizes[bucketIndex]  = 0;
        }

        size = 0;

        return this;
    }
}

