package com.cboe.client.util.collections;

/**
 * LongKeyPolicy.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyPolicy.java (KEY_TYPE=long)
 *
 */

public class LongKeyPolicy implements LongKeyPolicyIF
{
    public boolean canInsert(long key)
    {
        return true;
    }
    public boolean canRemove(long key)
    {
        return true;
    }
}

