package com.cboe.client.util.collections;

/**
 * LongIntKeyValuePolicy.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyValuePolicy.java (KEY_TYPE=long, VALUE_TYPE=int)
 *
 */

public class LongIntKeyValuePolicy implements LongIntKeyValuePolicyIF
{
    public boolean canInsert(long key, int newValue)
    {
        return true;
    }
    public boolean canUpdate(long key, int newValue, int oldValue)
    {
        return true;
    }
    public boolean canRemove(long key, int oldValue)
    {
        return true;
    }
}

