package com.cboe.client.util.collections;

/**
 * ObjectIntArrayHolder.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYArrayHolder.java (KEY_TYPE=Object, VALUE_TYPE=int)
 *
 */

import com.cboe.client.util.*;

public class ObjectIntArrayHolder implements ObjectIntArrayHolderIF
{
    public Object[]   keys;
    public int[] values;
    public int      size;

    public static final ObjectIntArrayHolderIF EmptyArrayHolder = new ObjectIntArrayHolder()
    {
        public void add(Object key, int value) {}
    };

    public ObjectIntArrayHolder()
    {
        this(0);
    }

    public ObjectIntArrayHolder(int capacity)
    {
        keys   = new Object[capacity];
        values = new int[capacity];
    }

    public int size()
    {
        return size;
    }

    public boolean isEmpty()
    {
        return size == 0;
    }

    public int capacity()
    {
        return keys.length;
    }

    public int ensureCapacity(int capacity)
    {
        if (keys.length < capacity)
        {
            keys   = CollectionHelper.arrayclone(keys,   0, keys.length,   capacity);
            values = CollectionHelper.arrayclone(values, 0, values.length, capacity);
        }

        return keys.length;
    }

    public Object[] keys()
    {
        return keys;
    }

    public Object[] getKeys()
    {
        return CollectionHelper.arrayclone(keys, size);
    }

    public int[] values()
    {
        return values;
    }

    public int[] getValues()
    {
        return CollectionHelper.arrayclone(values, size);
    }

    public void add(Object key, int value)
    {
        int newSize = size + 1;

        if (newSize >= keys.length)
        {
            keys   = CollectionHelper.arrayclone(keys,   0, keys.length,   newSize);
            values = CollectionHelper.arrayclone(values, 0, values.length, newSize);
        }

        keys[size]   = key;
        values[size] = value;

        size = newSize;
    }

    public Object getKey(int index)
    {
        if (index < size)
        {
            return keys[index];
        }

        return null;
    }

    public int getValue(int index)
    {
        if (index < size)
        {
            return values[index];
        }

        return IntegerHelper.INVALID_VALUE;
    }

    public boolean containsKey(Object key)
    {
        for (int i = 0; i < size; i++)
        {
            if (keys[i] == key || key.equals(keys[i]))
            {
                return true;
            }
        }

        return false;
    }

    public boolean containsValue(int value)
    {
        for (int i = 0; i < size; i++)
        {
            if (values[i] == value)
            {
                return true;
            }
        }

        return false;
    }

    public ObjectIntVisitorIF acceptVisitor(ObjectIntVisitorIF visitor)
    {
        for (int i = 0; i < size; i++)
        {
            visitor.visit(keys[i], values[i]);
        }

        return visitor;
    }

    public ObjectIntArrayHolderIF clear()
    {
        for (int i = 0; i < size; i++)
        {
            keys[i]   = null;
            values[i] = 0;
        }

        size = 0;

        return this;
    }
}

