package com.cboe.client.util.collections;

/**
 * ObjectIntVisitorIF
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYZVisitor.java (KEY_TYPE=Object, VALUE_TYPE=int)
 *
 */

public interface ObjectIntVisitorIF
{
    public static final int ABORT    = 0;
    public static final int CONTINUE = 1;
    public static final int SKIP     = 2;

    public int visit(Object key, int value);
}

