package com.cboe.client.util.collections;

/**
 * ObjectKeyPolicy.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyPolicy.java (KEY_TYPE=Object)
 *
 */

public class ObjectKeyPolicy implements ObjectKeyPolicyIF
{
    public boolean canInsert(Object key)
    {
        return true;
    }
    public boolean canRemove(Object key)
    {
        return true;
    }
}

