package com.cboe.client.util.collections;

/**
 * ObjectObjectKeyValuePolicy.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyValuePolicy.java (KEY_TYPE=Object, VALUE_TYPE=Object)
 *
 */

public class ObjectObjectKeyValuePolicy implements ObjectObjectKeyValuePolicyIF
{
    public boolean canInsert(Object key, Object newValue)
    {
        return true;
    }
    public boolean canUpdate(Object key, Object newValue, Object oldValue)
    {
        return true;
    }
    public boolean canRemove(Object key, Object oldValue)
    {
        return true;
    }
}

