package com.cboe.client.util.collections;

/**
 * ObjectArrayHolderIF.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XArrayHolderIF.java (KEY_TYPE=Object)
 *
 */

import com.cboe.client.util.*;

public interface ObjectArrayHolderIF extends HasSizeIF
{
    public int size();
    public boolean isEmpty();
    public int capacity();
    public int ensureCapacity(int capacity);
    public Object[] keys();
    public Object[] getKeys();
    public void add(Object key);
    public void add(Object[] keys);
    public void add(Object[] keys, int offset, int length);
    public Object getKey(int index);
    public boolean containsKey(Object key);
    public ObjectArrayHolderIF clear();
    public ObjectVisitorIF acceptVisitor(ObjectVisitorIF visitor);
}

