package com.cboe.client.util.collections;

/**
 * ObjectIntKeyValuePolicyIF.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyValuePolicyIF.java (KEY_TYPE=Object, VALUE_TYPE=int)
 *
 */

public interface ObjectIntKeyValuePolicyIF
{
    public boolean canInsert(Object key, int newValue);
    public boolean canUpdate(Object key, int newValue, int oldValue);
    public boolean canRemove(Object key, int oldValue);
}

