package com.cboe.client.util.collections;

/**
 * StringArrayHolderIF.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XArrayHolderIF.java (KEY_TYPE=String)
 *
 */

import com.cboe.client.util.*;

public interface StringArrayHolderIF extends HasSizeIF
{
    public int size();
    public boolean isEmpty();
    public int capacity();
    public int ensureCapacity(int capacity);
    public String[] keys();
    public String[] getKeys();
    public void add(String key);
    public void add(String[] keys);
    public void add(String[] keys, int offset, int length);
    public String getKey(int index);
    public boolean containsKey(String key);
    public StringArrayHolderIF clear();
    public ObjectVisitorIF acceptVisitor(ObjectVisitorIF visitor);
}

