package com.cboe.client.util.collections;

/**
 * StringKeyPolicy.java
 *
 * @author Dmitry Volpyansky
 *
 * FILE GENERATED BY VELOCITY TEMPLATE ENGINE FROM /vobs/dte/client/generator/DV_XYKeyPolicy.java (KEY_TYPE=String)
 *
 */

public class StringKeyPolicy implements StringKeyPolicyIF
{
    public boolean canInsert(String key)
    {
        return true;
    }
    public boolean canRemove(String key)
    {
        return true;
    }
}

