package com.cboe.exceptions;

import com.cboe.util.*;
/**
 * This class was generated by a SmartGuide.
 * 
 */
public class InvalidSideStringException extends CboeException {
/**
 * InvalidSideStringException constructor comment.
 */
public InvalidSideStringException() {
	super();
}
/**
 * InvalidSideStringException constructor comment.
 * @param s java.lang.String
 */
public InvalidSideStringException(String s) {
	super(s);
}
}
