whenever sqlerror continue

drop table SBTTRADENOTIFICATIONCONTRA;


CREATE TABLE SBTTRADENOTIFICATIONCONTRA
(
  DATABASEIDENTIFIER        NUMBER(20)         NOT NULL,
  TRADENOTIFICATIONDBID	    NUMBER(20)		NOT NULL,
  ORDERDBID		     		NUMBER(20),
  BRANCH					VARCHAR2(5),
  BRANCHSEQUENCENUMBER      NUMBER(10),
  CORRESPONDENTFIRM			VARCHAR2(5),
  ORDERDATE                 VARCHAR2(8),
  ORSID						VARCHAR2(6),
  TRADEDBID		     		NUMBER(20),
  EXECUTINGGIVEUPFIRM	    VARCHAR2(5),
  EXECUTINGGIVEUPFIRMEXCH   VARCHAR2(5),
  QUANTITY		     		NUMBER(20),
  CREAT_REC_TIME            TIMESTAMP(6)   DEFAULT systimestamp   
)
/* tablespace sbtb_me_data03 */
;

alter table SBTTRADENOTIFICATIONCONTRA
add constraint SBTTRADENOTIFICATIONCONTRA_PK
primary key (databaseIdentifier)
/* using index tablespace sbtb_me_indx03 */
;

create index SBTTRADENOTIFICATIONCONTRA_I1  
on SBTTRADENOTIFICATIONCONTRA(TRADENOTIFICATIONDBID)
/* using index tablespace sbtb_me_indx03 */
;