whenever sqlerror continue

drop table TABLE BSKT_TRADE_RELAT;

rem whenever sqlerror exit failure

CREATE TABLE  BSKT_TRADE_RELAT
(
DATABASEIDENTIFIER		NUMBER(20) NOT NULL,
BSKT_PROD_UID			NUMBER(20) NOT NULL,
SBT_TRADE_RPT_BSKT_UID		NUMBER(20) NOT NULL,
SBT_TRADE_RPT_BSKT_CMPNT_UID	NUMBER(20) NOT NULL,
BSKT_ASK_PRICE			NUMBER(20,8) NOT NULL,
BSKT_BID_PRICE			NUMBER(20,8) NOT NULL,
CREAT_REC_TIME			TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

alter table BSKT_TRADE_RELAT
add CONSTRAINT BSKT_TRADE_RELATpk PRIMARY KEY (DATABASEIDENTIFIER);

CREATE INDEX BSKT_TRADE_RELAT_I1 ON BSKT_TRADE_RELAT(CREAT_REC_TIME);