whenever sqlerror continue

drop table TABLE BSKT_PROD;

rem whenever sqlerror exit failure

CREATE TABLE BSKT_PROD
(
DATABASEIDENTIFIER	NUMBER(20) NOT NULL,
BSKT_TYPE		VARCHAR2(15) NOT NULL,
PRODUCTKEY		NUMBER(20) NOT NULL,
ACTV_DATE		VARCHAR2(8) NOT NULL,
LOW_EXER_PRICE		NUMBER(20, 8) NOT NULL,
HIGH_EXER_PRICE		NUMBER(20, 8) NOT NULL,
ATM_EXER_PRICE		NUMBER(20, 8) NOT NULL,
FWD_IDX_PRICE		NUMBER(20, 8) NOT NULL,
MIN_EXER_PRICE_INCR_AMT	NUMBER(20, 8) NOT NULL,
VOL_MULT_NBR		NUMBER(8) NOT NULL,
PRICE_MODEL_NAME	VARCHAR2(25) NOT NULL,
CREAT_REC_TIME		TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

alter table BSKT_PROD
add CONSTRAINT BSKT_PRODpk PRIMARY KEY (DATABASEIDENTIFIER);

CREATE INDEX BSKT_PROD_I1 ON BSKT_PROD(CREAT_REC_TIME);