whenever sqlerror continue

drop table TABLE BSKT_PROD_CMPNT;

rem whenever sqlerror exit failure

CREATE TABLE BSKT_PROD_CMPNT
(
DATABASEIDENTIFIER		NUMBER(20) NOT NULL,
BSKT_PROD_UID			NUMBER(20) NOT NULL,
PRODUCTKEY			NUMBER(20) NOT NULL,
CREAT_REC_TIME			TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

alter table BSKT_PROD_CMPNT
add CONSTRAINT BSKT_PROD_CMPNTpk PRIMARY KEY (DATABASEIDENTIFIER);

CREATE INDEX BSKT_PROD_CMPNT_I1 ON BSKT_PROD_CMPNT(CREAT_REC_TIME);