//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public class _QuotesStub
    extends org.omg.CORBA.portable.ObjectImpl
    implements NotifDemo.Quotes
{
    public _QuotesStub () {}

    public void auto_quote(int data) 
    {
        org.omg.CORBA.Request _req = this._request("auto_quote");
        _req.add_in_arg().insert_long(data);

        _req.send_oneway();

    }
    public void manual_quote() 
    {
        org.omg.CORBA.Request _req = this._request("manual_quote");
        _req.send_oneway();

    }
    public org.omg.CORBA.Object get_typed_consumer() 
    {
        org.omg.CORBA.Request _req = this._request("get_typed_consumer");
        org.omg.CORBA.Any _res = _req.return_value();
        _res.type(org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_objref));
        _req.invoke();

        return _res.extract_Object();
    }
    public void push(org.omg.CORBA.Any data) 
        throws org.omg.CosEventComm.Disconnected
    {
        org.omg.CORBA.Request _req = this._request("push");
        _req.exceptions().add(org.omg.CosEventComm.DisconnectedHelper.type());
        _req.add_in_arg().insert_any(data);

        _req.invoke();
        if (_req.env() != null && _req.env().exception() != null)
        {
            Exception _ex = _req.env().exception();
            if ( _ex  instanceof  org.omg.CORBA.UnknownUserException)
             {
                org.omg.CORBA.UnknownUserException  _userEx = (org.omg.CORBA.UnknownUserException)_ex;

                if (_userEx.except.type().equal(org.omg.CosEventComm.DisconnectedHelper.type()))
                {
                    throw org.omg.CosEventComm.DisconnectedHelper.extract(_userEx.except);
                }
                throw new org.omg.CORBA.MARSHAL(_ex.toString());
            }
        }

    }
    public void disconnect_push_consumer() 
    {
        org.omg.CORBA.Request _req = this._request("disconnect_push_consumer");
        _req.invoke();

    }
    public static final String _interfaces[] = 
      {"IDL:NotifDemo/Quotes:1.0", "IDL:org/omg/CosTypedEventComm/TypedPushConsumer:1.0", "IDL:org/omg/CosEventComm/PushConsumer:1.0"};

    public String[] _ids() {
        return _interfaces;
    }
    public java.lang.Object _deref() {
        return null;
    }

}
