//CONVERTED_BY_TRC
//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public abstract class POA_Quotes 
    extends org.omg.PortableServer.DynamicImplementation 
implements  QuotesOperations{
    protected POA_Quotes()
    {
        super();
    }

public Quotes _this() 
{  return QuotesHelper.narrow(super._this_object());
}
public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] oid)
{
	return _ids();
}
    public String[] _ids()
    {
        return _QuotesStub._interfaces;
    }
    public void invoke(org.omg.CORBA.ServerRequest _req)
    {
        _invoke(_req, this);
    }
    public static void _invoke(org.omg.CORBA.ServerRequest _req,POA_Quotes _obj)
    {
        String _opName = _req.op_name();
        org.omg.CORBA.Any _ret = _obj._orb().create_any();
        org.omg.CORBA.NVList _nvl = null;

        if (_opName.equals("auto_quote"))
        {
            _nvl = _obj._orb().create_list(1);

            org.omg.CORBA.Any data_ = _obj._orb().create_any();
            data_.type(org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_long));
            _nvl.add_value(null, data_, org.omg.CORBA.ARG_IN.value);

            _req.params(_nvl);


            _obj.auto_quote(data_.extract_long());




            return;
        }
        if (_opName.equals("manual_quote"))
        {
            _req.params(_nvl);


            _obj.manual_quote();




            return;
        }
        if (_opName.equals("get_typed_consumer"))
        {
            _ret = _obj._orb().create_any();
            _req.params(_nvl);


            org.omg.CORBA.Any __res = _obj._orb().create_any();
            _req.result(__res);
            __res.insert_Object(_obj.get_typed_consumer());




            return;
        }
        if (_opName.equals("push"))
        {
            _nvl = _obj._orb().create_list(1);

            org.omg.CORBA.Any data_ = _obj._orb().create_any();
            data_.type(org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_any));
            _nvl.add_value(null, data_, org.omg.CORBA.ARG_IN.value);

            _req.params(_nvl);


            try {
                _obj.push(data_.extract_any());


            } catch (org.omg.CosEventComm.Disconnected _ex) {
                org.omg.CosEventComm.DisconnectedHelper.insert(_ret,_ex);
                _req.except(_ret);
            }


            return;
        }
        if (_opName.equals("disconnect_push_consumer"))
        {
            _req.params(_nvl);


            _obj.disconnect_push_consumer();




            return;
        }
        else
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    public abstract void auto_quote(int data) ;

    public abstract void manual_quote() ;

    public abstract org.omg.CORBA.Object get_typed_consumer() ;

    public abstract void push(org.omg.CORBA.Any data) 
        throws org.omg.CosEventComm.Disconnected;

    public abstract void disconnect_push_consumer() ;

}
