//CONVERTED_BY_TRC
//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public interface QuotesOperations extends org.omg.CosTypedEventComm.TypedPushConsumerOperations {
    public void auto_quote(int data) ;

    public void manual_quote() ;

}
