//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public final class QuotesHolder
     implements org.omg.CORBA.portable.Streamable
{
    public NotifDemo.Quotes value;

    public QuotesHolder() {}

    public QuotesHolder(NotifDemo.Quotes value) {
        this.value = value;
    }
    public void _read (org.omg.CORBA.portable.InputStream _stream)
    {
        value = NotifDemo.QuotesHelper.read(_stream);
    }
    public void _write (org.omg.CORBA.portable.OutputStream _stream)
    {
        NotifDemo.QuotesHelper.write(_stream, value);
    }
    public org.omg.CORBA.TypeCode _type ()
    {
        return QuotesHelper.type();
    }
}
