package com.cboe.application.supplier.proxy;

import com.cboe.domain.instrumentorExtension.MethodInstrumentorExtension;
import com.cboe.domain.instrumentorExtension.MethodInstrumentorExtensionFactory;
import com.cboe.domain.instrumentorExtension.QueueInstrumentorExtension;
import com.cboe.domain.supplier.proxy.CallbackInterceptor;
import com.cboe.idl.cmiCallbackV2.CMINBBOConsumer;
import com.cboe.infrastructureServices.foundationFramework.utilities.Log;
import com.cboe.instrumentationService.factories.InstrumentorAlreadyCreatedException;
import com.cboe.instrumentationService.instrumentors.Instrumentor;
import com.cboe.interfaces.callback.NBBOV2Consumer;

/**
 * Generated by Java Grinder
 * @author Java Grinder
 */
public class NBBOV2ConsumerInterceptor extends CallbackInterceptor implements NBBOV2Consumer
{

    MethodInstrumentorExtension acceptNBBO0;
    CMINBBOConsumer cmiObject;

    /**
     * Create a new instance of ths interceptor for the provided BObject.
     * Create a cache of the instrumentors necessary for instrumentation.
     */
    public NBBOV2ConsumerInterceptor(CMINBBOConsumer o)
    {
        this.cmiObject = o;
    }

    /**
     */
    public void startInstrumentation(String prefix, boolean privateOnly)
    {
        try
        {
            StringBuilder name = new StringBuilder(prefix.length()+Instrumentor.NAME_DELIMITER.length()+15);
            name.append(prefix).append(Instrumentor.NAME_DELIMITER).append("acceptNBBO0");
            acceptNBBO0 = MethodInstrumentorExtensionFactory.createMethodInstrumentor(name.toString(), null, privateOnly);
        } catch (InstrumentorAlreadyCreatedException e)
        {
            Log.exception(e);
        }
    }

    /**
     *
     */
    public void removeInstrumentation()
    {
        if(acceptNBBO0 != null)
        {
            MethodInstrumentorExtensionFactory.removeMethodInstrumentor(acceptNBBO0.getName());
            acceptNBBO0 = null;
        }
    }

    /**
     *
     */
    public void addQueueInstrumentorRelation(QueueInstrumentorExtension queueInstrumentorExtension)
    {
        if(acceptNBBO0 != null)
        {
            acceptNBBO0.addQueueInstrumentorRelation(queueInstrumentorExtension);
        }
    }

    /**
     */
    public void acceptNBBO(com.cboe.idl.cmiMarketData.NBBOStruct[] param0, int param1, short param2)
    {
        boolean exception = false;
        if (acceptNBBO0 != null)
        {
            acceptNBBO0.beforeMethodCall();
        }
        try
        {
            cmiObject.acceptNBBO(param0, param1, param2);
        }
        catch (RuntimeException ex)
        {
            exception = true;
            throw ex;
        } finally
        {
            if (acceptNBBO0 != null)
            {
                acceptNBBO0.incCalls(1);
                acceptNBBO0.afterMethodCall();
                if (exception)
                {
                    acceptNBBO0.incExceptions(1);
                }
            }
        }
    }
}