package com.cboe.application.supplier.proxy;

import com.cboe.domain.instrumentorExtension.MethodInstrumentorExtension;
import com.cboe.domain.instrumentorExtension.MethodInstrumentorExtensionFactory;
import com.cboe.domain.instrumentorExtension.QueueInstrumentorExtension;
import com.cboe.domain.supplier.proxy.CallbackInterceptor;
import com.cboe.idl.cmiCallback.CMIProductStatusConsumer;
import com.cboe.infrastructureServices.foundationFramework.utilities.Log;
import com.cboe.instrumentationService.factories.InstrumentorAlreadyCreatedException;
import com.cboe.instrumentationService.instrumentors.Instrumentor;
import com.cboe.interfaces.callback.ProductStatusConsumer;

/**
 * Generated by Java Grinder
 * @author Java Grinder
 */
public class ProductStatusConsumerInterceptor extends CallbackInterceptor implements ProductStatusConsumer
{


    MethodInstrumentorExtension updateProduct1;

    MethodInstrumentorExtension acceptProductState0;
    CMIProductStatusConsumer cmiObject;

    /**
     * Create a new instance of ths interceptor for the provided BObject.
     * Create a cache of the instrumentors necessary for instrumentation.
     */
    public ProductStatusConsumerInterceptor(CMIProductStatusConsumer o)
    {
        this.cmiObject = o;
    }

    /**
     */
    public void startInstrumentation(String prefix, boolean privateOnly)
    {
        try
        {
            StringBuilder name = new StringBuilder(prefix.length()+Instrumentor.NAME_DELIMITER.length()+20);
            name.append(prefix).append(Instrumentor.NAME_DELIMITER).append("acceptProductState0");
            acceptProductState0 = MethodInstrumentorExtensionFactory.createMethodInstrumentor(name.toString(), null, privateOnly);
            name.setLength(0);
            name.append(prefix).append(Instrumentor.NAME_DELIMITER).append("updateProduct1");
            updateProduct1 = MethodInstrumentorExtensionFactory.createMethodInstrumentor(name.toString(), null, privateOnly);
        } catch (InstrumentorAlreadyCreatedException e)
        {
            Log.exception(e);
        }
    }

    /**
     *
     */
    public void removeInstrumentation()
    {
        if(acceptProductState0 != null)
        {
            MethodInstrumentorExtensionFactory.removeMethodInstrumentor(acceptProductState0.getName());
            acceptProductState0 = null;
        }
        if(updateProduct1 != null)
        {
            MethodInstrumentorExtensionFactory.removeMethodInstrumentor(updateProduct1.getName());
            updateProduct1 = null;
        }
    }

    /**
     *
     */
    public void addQueueInstrumentorRelation(QueueInstrumentorExtension queueInstrumentorExtension)
    {
        if(acceptProductState0 != null)
        {
            acceptProductState0.addQueueInstrumentorRelation(queueInstrumentorExtension);
        }
        if(updateProduct1 != null)
        {
            updateProduct1.addQueueInstrumentorRelation(queueInstrumentorExtension);
        }
    }

    /**
     */
    public void acceptProductState(com.cboe.idl.cmiSession.ProductStateStruct[] param0)
    {
        boolean exception = false;
        if (acceptProductState0 != null)
        {
            acceptProductState0.beforeMethodCall();
        }
        try
        {
            cmiObject.acceptProductState(param0);
        } catch (RuntimeException ex)
        {
            exception = true;
            throw ex;
        } finally
        {
            if (acceptProductState0 != null)
            {
                acceptProductState0.incCalls(1);
                acceptProductState0.afterMethodCall();
                if (exception)
                {
                    acceptProductState0.incExceptions(1);
                }
            }
        }
    }

    /**
     */
    public void updateProduct(com.cboe.idl.cmiSession.SessionProductStruct param0)
    {
        boolean exception = false;
        if (updateProduct1 != null)
        {
            updateProduct1.beforeMethodCall();
        }
        try
        {
            cmiObject.updateProduct(param0);
        } catch (RuntimeException ex)
        {
            exception = true;
            throw ex;
        } finally
        {
            if (updateProduct1 != null)
            {
                updateProduct1.incCalls(1);
                updateProduct1.afterMethodCall();
                if (exception)
                {
                    updateProduct1.incExceptions(1);
                }
            }
        }
    }
}