package com.cboe.application.supplier.proxy;

import com.cboe.domain.instrumentorExtension.MethodInstrumentorExtension;
import com.cboe.domain.instrumentorExtension.MethodInstrumentorExtensionFactory;
import com.cboe.domain.instrumentorExtension.QueueInstrumentorExtension;
import com.cboe.domain.supplier.proxy.CallbackInterceptor;
import com.cboe.idl.cmiCallbackV2.CMIRFQConsumer;
import com.cboe.infrastructureServices.foundationFramework.utilities.Log;
import com.cboe.instrumentationService.factories.InstrumentorAlreadyCreatedException;
import com.cboe.instrumentationService.instrumentors.Instrumentor;
import com.cboe.interfaces.callback.RFQV2Consumer;

/**
 * Generated by Java Grinder
 * @author Java Grinder
 */
public class RFQV2ConsumerInterceptor extends CallbackInterceptor implements RFQV2Consumer
{

    MethodInstrumentorExtension acceptRFQ0;
    CMIRFQConsumer cmiObject;

    /**
     * Create a new instance of ths interceptor for the provided BObject.
     * Create a cache of the instrumentors necessary for instrumentation.
     */
    public RFQV2ConsumerInterceptor(CMIRFQConsumer o)
    {
        this.cmiObject = o;
    }

    /**
     */
    public void startInstrumentation(String prefix, boolean privateOnly)
    {
        try
        {
            StringBuilder name = new StringBuilder(prefix.length()+Instrumentor.NAME_DELIMITER.length()+10);
            name.append(prefix).append(Instrumentor.NAME_DELIMITER).append("acceptRFQ0");
            acceptRFQ0 = MethodInstrumentorExtensionFactory.createMethodInstrumentor(name.toString(), null, privateOnly);
        } catch (InstrumentorAlreadyCreatedException e)
        {
            Log.exception(e);
        }
    }

    /**
     *
     */
    public void removeInstrumentation()
    {
        if(acceptRFQ0 != null)
        {
            MethodInstrumentorExtensionFactory.removeMethodInstrumentor(acceptRFQ0.getName());
            acceptRFQ0 = null;
        }
    }

    /**
     *
     */
    public void addQueueInstrumentorRelation(QueueInstrumentorExtension queueInstrumentorExtension)
    {
        if(acceptRFQ0 != null)
        {
            acceptRFQ0.addQueueInstrumentorRelation(queueInstrumentorExtension);
        }
    }

    /**
     */
    public void acceptRFQ(com.cboe.idl.cmiQuote.RFQStruct[] param0, int param1, short param2)
    {
        boolean exception = false;
        if (acceptRFQ0 != null)
        {
            acceptRFQ0.beforeMethodCall();
        }
        try
        {
            cmiObject.acceptRFQ(param0, param1, param2);
        }
        catch (RuntimeException ex)
        {
            exception = true;
            throw ex;
        } finally
        {
            if (acceptRFQ0 != null)
            {
                acceptRFQ0.incCalls(1);
                acceptRFQ0.afterMethodCall();
                if (exception)
                {
                    acceptRFQ0.incExceptions(1);
                }
            }
        }
    }
}