package com.cboe.application.supplier.proxy;

import com.cboe.domain.instrumentorExtension.MethodInstrumentorExtension;
import com.cboe.domain.instrumentorExtension.MethodInstrumentorExtensionFactory;
import com.cboe.domain.instrumentorExtension.QueueInstrumentorExtension;
import com.cboe.domain.supplier.proxy.CallbackInterceptor;
import com.cboe.idl.cmiCallback.CMITradingSessionStatusConsumer;
import com.cboe.infrastructureServices.foundationFramework.utilities.Log;
import com.cboe.instrumentationService.factories.InstrumentorAlreadyCreatedException;
import com.cboe.instrumentationService.instrumentors.Instrumentor;
import com.cboe.interfaces.callback.TradingSessionStatusConsumer;

/**
 * Generated by Java Grinder
 * @author Java Grinder
 */
public class TradingSessionStatusConsumerInterceptor extends CallbackInterceptor implements TradingSessionStatusConsumer
{

    MethodInstrumentorExtension acceptTradingSessionState0;
    CMITradingSessionStatusConsumer cmiObject;

    /**
     * Create a new instance of ths interceptor for the provided BObject.
     * Create a cache of the instrumentors necessary for instrumentation.
     */
    public TradingSessionStatusConsumerInterceptor(CMITradingSessionStatusConsumer o)
    {
        this.cmiObject = o;
    }

    /**
     */
    public void startInstrumentation(String prefix, boolean privateOnly)
    {
        try
        {
            StringBuilder name = new StringBuilder(prefix.length()+Instrumentor.NAME_DELIMITER.length()+26);
            name.append(prefix).append(Instrumentor.NAME_DELIMITER).append("acceptTradingSessionState0");
            acceptTradingSessionState0 = MethodInstrumentorExtensionFactory.createMethodInstrumentor(name.toString(), null, privateOnly);
        } catch (InstrumentorAlreadyCreatedException e)
        {
            Log.exception(e);
        }
    }

    /**
     *
     */
    public void removeInstrumentation()
    {
        if(acceptTradingSessionState0 != null)
        {
            MethodInstrumentorExtensionFactory.removeMethodInstrumentor(acceptTradingSessionState0.getName());
            acceptTradingSessionState0 = null;
        }
    }

    /**
     *
     */
    public void addQueueInstrumentorRelation(QueueInstrumentorExtension queueInstrumentorExtension)
    {
        if(acceptTradingSessionState0 != null)
        {
            acceptTradingSessionState0.addQueueInstrumentorRelation(queueInstrumentorExtension);
        }
    }

    /**
     */
    public void acceptTradingSessionState(com.cboe.idl.cmiSession.TradingSessionStateStruct param0)
    {
        boolean exception = false;
        if (acceptTradingSessionState0 != null)
        {
            acceptTradingSessionState0.beforeMethodCall();
        }
        try
        {
            cmiObject.acceptTradingSessionState(param0);
        } catch (RuntimeException ex)
        {
            exception = true;
            throw ex;
        } finally
        {
            if (acceptTradingSessionState0 != null)
            {
                acceptTradingSessionState0.incCalls(1);
                acceptTradingSessionState0.afterMethodCall();
                if (exception)
                {
                    acceptTradingSessionState0.incExceptions(1);
                }
            }
        }
    }
}