column DbID format 99999999999999999999;
set line 190;
set pagesize 10000;
select
 DATABASEIDENTIFIER  DbID,
 EXECUTINGORGIVEUPFIRM   EFirm,
 EXECUTINGORGIVEUPFIRMEXCH   EFExch,
 BRANCH   Brch, 
 BRANCHSEQUENCENUMBER  BrchSeq,
 CORRESPONDENTFIRM   CFirm,
 ORDERDATE,
 to_char(convert_java_time( RECEIVEDTIME), 'YY-MM-DD-HH24:MI:SS')  RecT,
 ORIGINALQUANTITY   OQTY,
 TIMEINFORCE   T,
 STATE  ST,
 TRADEDQUANTITY   TQTY,
 CANCELLEDQUANTITY  CQTY,
 ADDEDQUANTITY  AQTY,
 ProductKey    PKEY,
 SIDE  Side,
 PRICE,
 ORSID, 
 SOURCE,
 ORDERORIGINTYPE  Orig,
 USERID
 FROM SBTORDER
WHERE UserId  = '&1'
AND  convert_java_time( RECEIVEDTIME) between to_date('&2-&3', 'YYYY-MM-DD-hh24:mi:ss')
	AND  to_date('&2-&4', 'YYYY-MM-DD-hh24:mi:ss') 
;
