column DbID format 99999999999999999999;
set line 190;

select
 DATABASEIDENTIFIER as DbID,
 EXECUTINGORGIVEUPFIRM  as EFirm,
 EXECUTINGORGIVEUPFIRMEXCH  as EFExch,
 BRANCH   as Brch, 
 BRANCHSEQUENCENUMBER as BrchSeq,
 CORRESPONDENTFIRM  as CFirm,
 ORDERDATE,
 to_char(convert_java_time( RECEIVEDTIME), 'YY-MM-DD HH24:MI:SS') as RecT,
 ORIGINALQUANTITY  as OQTY,
 TIMEINFORCE  as T,
 STATE as ST,
 TRADEDQUANTITY  as TQTY,
 CANCELLEDQUANTITY as CQTY,
 ADDEDQUANTITY as AQTY,
 ProductKey   as PKEY,
 SIDE as Side,
 PRICE as PRICE,
 ORSID, 
 SOURCE,
 ORDERORIGINTYPE as Orig,
 USERID
 FROM SBTORDER
WHERE BRANCH  = '&1'
AND BRANCHSEQUENCENUMBER  = &2
;

