Column DbID format 99999999999999999999;
set line 190;
set pagesize 10000;
select
 DATABASEIDENTIFIER as DbID,
 EXECUTINGORGIVEUPFIRM  as EFirm,
 EXECUTINGORGIVEUPFIRMEXCH  as EFExch,
 BRANCH   as Brch, 
 BRANCHSEQUENCENUMBER as BrchSeq,
 CORRESPONDENTFIRM  as CFirm,
 ORDERDATE,
 to_char(convert_java_time( RECEIVEDTIME), 'YYYY-MM-DD HH24:MI:SS') as RecT,
 ProductKey,
 ORIGINALQUANTITY  as OQTY,
 TIMEINFORCE  as T,
 STATE as ST,
 TRADEDQUANTITY  as TQTY,
 CANCELLEDQUANTITY as CQTY,
 PRICE as PRICE,
 ORSID, SOURCE,
 ORDERORIGINTYPE as Orig,
 SIDE,
 USERID
from sbtorder where CLASSKEY= &1 and TIMEINFORCE = 'G' order by RECEIVEDTIME ;
