//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public interface _QuotesOperations extends org.omg.CosTypedEventComm._TypedPushConsumerOperations {
    public void auto_quote(int data) ;

    public void manual_quote() ;

}
