//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public class _tie_Quotes 
    extends _QuotesSkeleton 
    implements Quotes 
{
    protected _QuotesOperations m_impl;

    public _tie_Quotes(_QuotesOperations impl) {
        this.m_impl = impl;
    }

    public void auto_quote(int data) {
        m_impl.auto_quote(data);
    }

    public void manual_quote() {
        m_impl.manual_quote();
    }

    public org.omg.CORBA.Object get_typed_consumer() {
        return m_impl.get_typed_consumer();
    }

    public void push(org.omg.CORBA.Any data) 
        throws org.omg.CosEventComm.Disconnected{
        m_impl.push(data);
    }

    public void disconnect_push_consumer() {
        m_impl.disconnect_push_consumer();
    }

    public java.lang.Object _deref() {
        return m_impl;
    }

}
