//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public class QuotesHelper
{
    public static void insert (org.omg.CORBA.Any any, NotifDemo.Quotes value)
    {
        any.insert_Streamable(new NotifDemo.QuotesHolder(value));
    }
    public static NotifDemo.Quotes extract (org.omg.CORBA.Any any)
    {
        if (!any.type().equal(type())) 
            throw new org.omg.CORBA.BAD_TYPECODE("Error inserting/extracting value from typecode.");
        else
            return read(any.create_input_stream()); 
    }
    private static org.omg.CORBA.TypeCode _type;
    public static org.omg.CORBA.TypeCode type()
    {
        if (_type == null) {
            _type =  org.omg.CORBA.ORB.init().create_interface_tc(NotifDemo.QuotesHelper.id(),"Quotes");
        }
        return _type;
    }
    public static org.omg.CORBA.ORB _orb () {
        return org.omg.CORBA.ORB.init(); 
    }
    public static String id () {
        return "IDL:NotifDemo/Quotes:1.0";
    }
    public static NotifDemo.Quotes read (org.omg.CORBA.portable.InputStream _stream)
    {
        return (narrow (_stream.read_Object()));
    }
    public static void write (org.omg.CORBA.portable.OutputStream _stream, NotifDemo.Quotes value)
    {
        _stream.write_Object(value);
    }
    public static NotifDemo.Quotes narrow (org.omg.CORBA.Object _obj)
        throws org.omg.CORBA.BAD_PARAM
    {
        if (_obj == null)
        {
            return null;
        }
        if (_obj instanceof NotifDemo._QuotesStub){
            return (NotifDemo._QuotesStub)_obj;
        }
        if (_obj instanceof NotifDemo.Quotes)
        {
            return (NotifDemo.Quotes)_obj;
        }
        if (_obj._is_a(id()))
        {
            NotifDemo._QuotesStub _ref = new NotifDemo._QuotesStub();
            _ref._set_delegate(((org.omg.CORBA.portable.ObjectImpl)_obj)._get_delegate());
            return _ref;
        }
        else
            throw new org.omg.CORBA.BAD_PARAM();
    }
}
