//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public class QuoteStructHelper
{
    public static void insert (org.omg.CORBA.Any any, NotifDemo.QuoteStruct value)
    {
        any.insert_Streamable(new NotifDemo.QuoteStructHolder(value));
    }
    public static NotifDemo.QuoteStruct extract (org.omg.CORBA.Any any)
    {
        if (!any.type().equal(type())) 
            throw new org.omg.CORBA.BAD_TYPECODE("Error inserting/extracting value from typecode.");
        else
            return read(any.create_input_stream()); 
    }
    private static org.omg.CORBA.TypeCode _type;
    public static org.omg.CORBA.TypeCode type()
    {
        if (_type == null) {
            org.omg.CORBA.StructMember[] _s = new org.omg.CORBA.StructMember[2];
            _s[0] = new org.omg.CORBA.StructMember("product",org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_string),null);
            _s[1] = new org.omg.CORBA.StructMember("price",org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_float),null);
            _type =  org.omg.CORBA.ORB.init().create_struct_tc(NotifDemo.QuoteStructHelper.id(),"QuoteStruct",_s);
        }
        return _type;
    }
    public static org.omg.CORBA.ORB _orb () {
        return org.omg.CORBA.ORB.init(); 
    }
    public static String id () {
        return "IDL:NotifDemo/QuoteStruct:1.0";
    }
    public static NotifDemo.QuoteStruct read (org.omg.CORBA.portable.InputStream _stream)
    {
        NotifDemo.QuoteStruct value = new NotifDemo.QuoteStruct();
        value.product = _stream.read_string();
        value.price = _stream.read_float();
        return value;
    }
    public static void write (org.omg.CORBA.portable.OutputStream _stream, NotifDemo.QuoteStruct value)
    {
        _stream.write_string(value.product);
        _stream.write_float(value.price);
    }
}
