//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public interface Quotes
    extends org.omg.CosTypedEventComm.TypedPushConsumer
{
    public void auto_quote(int data) ;

    public void manual_quote() ;

    public java.lang.Object _deref() ;
}
