//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public final class QuoteStruct 
    implements java.lang.Cloneable 
{
    public String product;
    public float price;

    public QuoteStruct () {}

    public QuoteStruct (String product,float price) {
        this.product = product;
        this.price = price;
    }

    public java.lang.Object clone()
    {
        NotifDemo.QuoteStruct _dest;
        try {
            _dest = (NotifDemo.QuoteStruct)super.clone();
            if (product != null)
                _dest.product = new String(product);
        } catch (java.lang.CloneNotSupportedException _ex) {
            throw new java.lang.Error(_ex.getMessage());
        }
        return _dest;
    }
}
