//
// Java generated by the OrbixWeb IDL compiler 
//

package NotifDemo;


public final class QuoteSequenceHolder
     implements org.omg.CORBA.portable.Streamable
{
    public NotifDemo.QuoteStruct[] value;

    public QuoteSequenceHolder() {}

    public QuoteSequenceHolder(NotifDemo.QuoteStruct[] value) {
        this.value = value;
    }
    public void _read (org.omg.CORBA.portable.InputStream _stream)
    {
        value = NotifDemo.QuoteSequenceHelper.read(_stream);
    }
    public void _write (org.omg.CORBA.portable.OutputStream _stream)
    {
        NotifDemo.QuoteSequenceHelper.write(_stream, value);
    }
    public org.omg.CORBA.TypeCode _type ()
    {
        return QuoteSequenceHelper.type();
    }
}
