BEGIN {
	print "      CPU Usage Threshold Report"	
	print "         Threshold = 60 %  "
	print "======================================"
}
/%/	{ if ( substr($3,1,length($3)-1) >= 60 ) 
		if ( ! (substr($2,1,2)>="15" && substr($2,4,2) > 15) )
			printf( "Server: %s ===> %s at %s\n",$1,$3,$2)
		}
/,,/	{ printf ("Data not found for Server: %s\n",$1) }

END {
	print "\nGenerated by clientCPU_report.ksh"
}
