#!/bin/ksh
# Calculate date for specified previous day of week
# Usage: OTHER_DAY=$( $0 day-of-week )
# Example: $0 Sunday     # get date for last Sunday

# -------------------- Subroutines --------------------

# Set dow to day-of-week number
# @param 1 name of day, full or abbreviated
# @return dow=0 for Sunday, 1 for Monday, ... 6 for Saturday
dowNum()
{
    typeset -l day=$1
    case $day in
    su*)
        dow=0
        ;;
    mo*)
        dow=1
        ;;
    tu*)
        dow=2
        ;;
    we*)
        dow=3
        ;;
    th*)
        dow=4
        ;;
    fr*)
        dow=5
        ;;
    sa*)
        dow=6
        ;;
    esac
}

# -------------------- Main program --------------------

dowNum $( date +%a )
integer Today=$dow

dowNum $1
integer EarlierDay=$dow

integer Year=$( date +%Y )
integer Month=$( date +%m )
integer Day=$( date +%d )

if [ $EarlierDay -ge $Today ] ; then
    Today=$Today+7
fi

integer Diff=$Today-$EarlierDay
if [ $Day -le $Diff ] ; then
    # EarlierDay is in previous month
    if [ $Month -eq 1 ] ; then
        # Previous month is in previous year
        Month=12
        Year=$Year-1
    else
        Month=$Month-1
    fi

    # Add current day to days in previous month (example June 2 => May 33)
    case $Month in
    1|3|5|7|8|10|12)
        Day=31+$Day
        ;;
    4|6|9|11)
        Day=30+$Day
        ;;
    2)
        # February!
        integer quadcentury=$Year%400
        integer century=$Year%100
        integer quad=$Year%4
        if [ $quadcentury -eq 0 ] ; then
            Day=29+$Day
        elif [ $century -eq 0 ] ; then
            Day=28+$Day
        elif [ $quad -eq 0 ] ; then
            Day=29+$Day
        else
            Day=28+$Day
        fi
        ;;
    esac
fi # Day

Day=$Day-$Diff

typeset -Z2 M=$Month
typeset -Z2 D=$Day
echo "$Year/$M/$D"
