#ifndef CMI_EVENTS_V5_IDL
#define CMI_EVENTS_V5_IDL
//---------------------------------------------------------------------------------------------
// Company:      Chicago Board Options Exchange
// Version:      Version 8.0
//
// Copyright © 1999-2006 by the Chicago Board Options Exchange ("CBOE"), as an unpublished work.
// The information contained in this software program constitutes confidential and/or trade
// secret information belonging to CBOE. This software program is made available to
// CBOE members and member firms to enable them to develop software applications using
// the CBOE Market Interface (CMi), and its use is subject to the terms and conditions
// of a Software License Agreement that governs its use. This document is provided "AS IS"
// with all faults and without warranty of any kind, either express or implied.
//---------------------------------------------------------------------------------------------

#include "cmiConstants.idl"
#include "cmiProduct.idl"

#pragma javaPackage "com.cboe.idl"

module cmiCallbackV5
{
	interface CMITradingClassStatusQueryConsumer {
		void acceptTradingClassStatusUpdateforProductGroups(
            	in cmiProduct::ProductGroupSequence listOfProductGroups,
            	in cmiUtil::TradingClassStatusIndicator status);
        		
		void acceptTradingClassStatusUpdateforClasses(
            	in cmiProduct::ClassKeySequence listOfClasses,
            	in cmiUtil::TradingClassStatusIndicator status);
	};
};

#endif
