#ifndef EXCEPTIONS_IDL
#define EXCEPTIONS_IDL
//---------------------------------------------------------------------------------------------
// Company:      Chicago Board Options Exchange
// Version:      1.0
//
// Copyright © 1999-2001 by the Chicago Board Options Exchange ("CBOE"), as an unpublished work.
// The information contained in this software program constitutes confidential and/or trade
// secret information belonging to CBOE. This software program is made available to
// CBOE members and member firms to enable them to develop software applications using
// the CBOE Market Interface (CMi), and its use is subject to the terms and conditions
// of a Software License Agreement that governs its use. This document is provided "AS IS"
// with all faults and without warranty of any kind, either express or implied.
//---------------------------------------------------------------------------------------------


#pragma javaPackage "com.cboe.ffidl"

module ffExceptions
{
    typedef long ErrorCode;

    typedef short SeverityLevel;

    struct ExceptionDetails {
        string message;
        string dateTime;
        SeverityLevel severity;
        ErrorCode error;
    };

    exception AlreadyExistsException {
        ExceptionDetails details;
    };

    exception AuthorizationException {
        ExceptionDetails details;
    };

    exception AuthenticationException {
        ExceptionDetails details;
    };

    exception CommunicationException {
        ExceptionDetails details;
    };

    exception DataValidationException {
        ExceptionDetails details;
    };

    exception NotFoundException {
        ExceptionDetails details;
    };

    exception NotAcceptedException {
        ExceptionDetails details;
    };

    exception NotSupportedException {
        ExceptionDetails details;
    };

    exception SystemException {
        ExceptionDetails details;
    };
    exception TransactionFailedException {
        ExceptionDetails details;
    };

};
#endif
