
TEST_DATA=rpt_class\
	configurationGroup\
	configurationGroupType\
	exchange\
	groupClassRelationship\
	parentChildRelationship\
	childParentRelationship\
	product\
	prod_class\
	prod_comp\
	prod_desc\
	prod_type\
	profile\
	clearing_Acr\
	property\
	property_group\
	trading_session_template\
	trading_session\
	trading_property\
	sbt_user\
	firm\
	user_account_relation\
	user_firm_relation\
    user_firm_affiliation\
	asgn_class\
	uuid\
        login_userid\
	group_element\
	group_relationship

TABLE_DDL_FILES=ConvertDate.sql\
	ConvertJavaTime.sql\
	Preference.sql\
	Product.sql\
	ProductClass.sql\
	ProductType.sql\
	ReportingClass.sql\
	User.sql\
	UserEnablement.sql\
	BestQuote.sql\
	CurrentQuotes.sql\
	MarketData.sql\
	MarketDataSummary.sql\
	MarketDataHistoryEntry.sql\
	SbtQuoteHistory.sql\
	SbtTradeHistory.sql\
	createSbtOrder.sql\
	createSbtOrderLegDetail.sql\
	createSbtOrderHistory.sql\
	tradeReport.sql\
	tradeReportEntry.sql\
	CurrentMarket.sql\
	PriceAdjustment.sql\
	ProductAdjustment.sql\
	Recap.sql\
	ReportingClassAdjustment.sql\
	AssignedClass.sql\
	AssignedClassHistory.sql\
	Exchange.sql\
	Firm.sql\
	MembershipRefreshTime.sql\
	ProductComponent.sql\
	ProductDescription.sql\
	QueueElementTable.sql\
	QueueTable.sql\
	Quote.sql\
	TradeReportAck.sql\
	TradingProperty.sql\
	BusinessDay.sql\
	TradingSessionElementTemplate.sql\
	TradingSession.sql\
	TradingSessionElement.sql\
	TransactionFeeCode.sql\
	TemplateClass.sql\
	SessionElementClass.sql\
	SessionElementProduct.sql\
	ChildRelationship.sql\
	ConfigurationGroup.sql\
	ConfigurationGroupType.sql\
	GroupClassRelationship.sql\
	ParentRelationship.sql\
	Profile.sql\
	clearingAcr.sql\
	Receipient.sql\
	ReceipientTextMessage.sql\
	ReceipientTextMessageBackup.sql\
	TradingClass.sql\
	TradingProduct.sql\
	UserAccountRelation.sql\
	UserFirmRelation.sql\
	UserSessionAuthorization.sql\
	textMessage.sql\
	textMessageBackup.sql\
	textMessageTemplate.sql\
	quoteRiskProfile.sql\
	RFQHistory.sql\
	OrderBook.sql\
	OrderBookSideItem.sql\
	OrderBookPriceItem.sql\
	OrderBookPriceDetail.sql\
	tradingSessionEventHist.sql\
	OrderBookPriceDetail.sql\
	UserReportRegisteredUser.sql\
	UserReport.sql\
	UserReportAck.sql\
	sequencers.sql\
	FormatSettlementPrice.sql\
	createGlobalUidSequence.sql\
	ConvertJavaTime.sql\
	GetTimeZone.sql\
	order_id_seed.sql\
	NBBOAgentMap.sql\
	SbtAgentAssignedOrder.sql\
	IntermarketTextMessage.sql\
	alert.sql\
	OrderExchangeMarket.sql\
	OrderMarketMonitor.sql\
	AlertExchangeMarket.sql\
	tradingSessionRegMap.sql\
	tradingSessionEventHistDetail.sql\
	Property.sql\
	PropertyGroup.sql\
	createOrderRelationship.sql\
	createTradedThroughOrders.sql\
	createSbtAuction.sql\
	createSIACReferenceTable.sql\
	UserSmartCache.sql\
	UserFirmAffiliation.sql\
        loginUserid.sql\
	GroupElement.sql\
	GroupRelationship.sql\
	BulkActionRequest.sql\
	SbtORSIDExclusion.sql\
	createLinkageOrderRelationship.sql\
	BulkActionDtl.sql\
	createSbtRoutedMessage.sql\
	market_data_hist_for_reports.sql\
	createSbtTradeNotificationContra.sql\
	createSbtTradeNotification.sql\
	createAuctionOrderRelationship.sql\
	recap_for_reports.sql\
	mkt_hist_reports_archive.sql\
	recap_reports_archive.sql\
	createBasketProduct.sql\
	createBasketProductComponent.sql\
	createBasketTradeRelation.sql\
